// runtime_kubernetes_destroy.go — Destroy for the kubernetes adapter (ADR 0106
// decision 5): remove the claims, and report every volume it cannot confirm gone.
package runtime

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"slices"
	"sort"
	"time"
)

// kubeAnnInventory is Destroy's record on the StatefulSet: each claim's UID and bound
// volume, and whether that volume carried a deletion-protection finalizer. The
// StatefulSet is the last thing Destroy deletes, so a CP that dies anywhere after the
// record is written finds it again: a volume name is generated by the provisioner and
// cannot be listed back through the namespaced role.
const kubeAnnInventory = "agent-fleet.io/destroy-inventory"

// kubeDestroyClaimBudget bounds Destroy's wait for the claims and their volumes to go.
// A variable so a test can shorten it.
var kubeDestroyClaimBudget = 2 * time.Minute

// kubeVolumeProtection are the finalizers that hold a PersistentVolume object until the
// disk behind it is deleted: the CSI provisioner's, and the in-tree controller's. A
// volume that carried neither proves nothing by disappearing.
var kubeVolumeProtection = []string{
	"external-provisioner.volume.kubernetes.io/finalizer",
	"kubernetes.io/pv-controller",
}

type kubeInventory struct {
	Claims  map[string]kubeInvClaim  `json:"claims"`
	Volumes map[string]kubeInvVolume `json:"volumes"`
}

type kubeInvClaim struct {
	UID    string `json:"uid"`
	Volume string `json:"volume,omitempty"`
}

type kubeInvVolume struct {
	// Protected: the volume carried a deletion-protection finalizer when it was
	// inventoried, so its object going means its disk went.
	Protected bool `json:"protected"`
}

// readInventory returns the record on s, extended rather than replaced by every run. A
// record that cannot be read is reported as such: rebuilding it from claims that may
// already be gone would forget their volumes.
func readInventory(s *kStatefulSet) (kubeInventory, bool) {
	inv := kubeInventory{Claims: map[string]kubeInvClaim{}, Volumes: map[string]kubeInvVolume{}}
	if s == nil {
		return inv, true
	}
	raw := s.Metadata.Annotations[kubeAnnInventory]
	if raw == "" {
		return inv, true
	}
	if err := json.Unmarshal([]byte(raw), &inv); err != nil {
		return kubeInventory{Claims: map[string]kubeInvClaim{}, Volumes: map[string]kubeInvVolume{}}, false
	}
	if inv.Claims == nil {
		inv.Claims = map[string]kubeInvClaim{}
	}
	if inv.Volumes == nil {
		inv.Volumes = map[string]kubeInvVolume{}
	}
	return inv, true
}

// Destroy stops the workspace (Stop returns only once the stop has settled), deletes a
// leftover erase pod, records the inventory on the StatefulSet, deletes the Service, the
// Secret and both claims, and waits a bounded time for the claims and every inventoried
// volume to go. It deletes the StatefulSet only when all of them are confirmed gone;
// otherwise the StatefulSet stays, inventory and all, and the residue lists it with
// everything unconfirmed: `statefulset:<ns>/<name>`, `pvc:<ns>/<name>`, `pv:<name>`.
//
// Every step starts from what the cluster shows, so a Destroy interrupted before it
// returned is completed by running it again.
func (k *kubeRuntime) Destroy(ctx context.Context) ([]string, error) {
	if err := k.Stop(ctx); err != nil {
		return nil, err
	}
	s, err := k.getStatefulSet(ctx)
	if err != nil {
		return nil, fmt.Errorf("kubernetes destroy %s: %w", k.base, err)
	}
	// The erase pod holds the home claim through its protection finalizer.
	if err := k.c.delete(ctx, k.podPath(k.erasePodName())); err != nil {
		return nil, fmt.Errorf("kubernetes destroy %s: delete the erase pod: %w", k.base, err)
	}
	inv, readable := readInventory(s)
	claimPath := k.nsPath("") + "/persistentvolumeclaims/"
	claims := []string{k.homeClaim(), k.stateClaim()}
	var present []string
	for _, name := range claims {
		var pvc kPVC
		err := k.c.get(ctx, claimPath+name, &pvc)
		if isKubeNotFound(err) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("kubernetes destroy %s: claim %s: %w", k.base, name, err)
		}
		present = append(present, name)
		inv.Claims[name] = kubeInvClaim{UID: pvc.Metadata.UID, Volume: pvc.Spec.VolumeName}
		if v := pvc.Spec.VolumeName; v != "" {
			if _, seen := inv.Volumes[v]; !seen {
				inv.Volumes[v] = kubeInvVolume{Protected: k.volumeProtected(ctx, v)}
			}
		}
	}
	if s != nil && readable {
		raw, _ := json.Marshal(inv)
		if err := k.c.mergePatch(ctx, k.stsPath(), map[string]any{
			"metadata": map[string]any{"annotations": map[string]string{kubeAnnInventory: string(raw)}},
		}, nil); err != nil {
			return nil, fmt.Errorf("kubernetes destroy %s: record the inventory: %w", k.base, err)
		}
	}
	if err := k.c.delete(ctx, k.nsPath("")+"/services/"+k.base); err != nil {
		return nil, fmt.Errorf("kubernetes destroy %s: delete service: %w", k.base, err)
	}
	if err := k.c.delete(ctx, k.nsPath("")+"/secrets/"+k.secretName()); err != nil {
		return nil, fmt.Errorf("kubernetes destroy %s: delete secret: %w", k.base, err)
	}
	// From here on nothing returns an error: the claims are being deleted, and what does
	// not go must reach the audit log as a residue.
	for _, name := range present {
		if err := k.c.delete(ctx, claimPath+name); err != nil {
			log.Printf("kubernetes destroy %s: delete claim %s: %v", k.base, name, err)
		}
	}
	ns := k.cfg.namespace
	pending := map[string]string{} // residue -> object path
	for _, name := range present {
		pending["pvc:"+ns+"/"+name] = claimPath + name
	}
	for v := range inv.Volumes {
		pending["pv:"+v] = "/api/v1/persistentvolumes/" + v
	}
	deadline := time.Now().Add(kubeDestroyClaimBudget)
	for len(pending) > 0 {
		for res, path := range pending {
			var obj struct {
				Metadata kObjectMeta `json:"metadata"`
			}
			if err := k.c.get(ctx, path, &obj); isKubeNotFound(err) {
				delete(pending, res)
			}
		}
		if len(pending) == 0 || time.Now().After(deadline) || ctx.Err() != nil {
			break
		}
		select {
		case <-ctx.Done():
		case <-time.After(k.poll):
		}
	}
	var residues []string
	for res := range pending {
		residues = append(residues, res)
	}
	// A volume object gone without a deletion-protection finalizer is no proof the disk
	// went (ADR 0106 decision 5).
	for v, iv := range inv.Volumes {
		if !iv.Protected && !slices.Contains(residues, "pv:"+v) {
			residues = append(residues, "pv:"+v)
		}
	}
	// Start creates both claims before the StatefulSet, so a claim missing now and absent
	// from the inventory was removed by something that did not record its volume.
	known := readable
	for _, name := range claims {
		if _, ok := inv.Claims[name]; !ok && s != nil {
			known = false
		}
	}
	sort.Strings(residues)
	if s == nil {
		k.setPhase("")
		return residues, nil
	}
	if len(residues) > 0 || !known {
		return append(residues, "statefulset:"+ns+"/"+k.base), nil
	}
	if err := k.c.delete(ctx, k.stsPath()); err != nil {
		log.Printf("kubernetes destroy %s: delete statefulset: %v", k.base, err)
		return []string{"statefulset:" + ns + "/" + k.base}, nil
	}
	k.setPhase("")
	return nil, nil
}

// volumeProtected reads the volume through the CP's read-only cluster access. Unreadable
// is unprotected: the answer that keeps the volume in the residue.
func (k *kubeRuntime) volumeProtected(ctx context.Context, name string) bool {
	var pv kPV
	if err := k.c.get(ctx, "/api/v1/persistentvolumes/"+name, &pv); err != nil {
		return false
	}
	for _, f := range pv.Metadata.Finalizers {
		if slices.Contains(kubeVolumeProtection, f) {
			return true
		}
	}
	return false
}
