package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func pattern(t *testing.T) *Linter {
	t.Helper()
	pat, err := LoadPattern("patterns.txt")
	if err != nil {
		t.Fatal(err)
	}
	return &Linter{Pattern: pat, Registry: map[string]bool{"mod/registry/r.go": true}, Root: t.TempDir()}
}

func write(t *testing.T, root, rel, body string) {
	t.Helper()
	p := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func statuses(fs []Finding) map[string]Status {
	m := map[string]Status{}
	for _, f := range fs {
		m[f.Path+":"+f.Literal] = f.Status
	}
	return m
}

// The pattern is the whole definition of "model-id-shaped", so pin both sides of it with the
// real spellings it was drawn from and the near-misses it must leave alone.
func TestPatternMatchesIDsAndNotTheirNeighbours(t *testing.T) {
	l := pattern(t)
	for _, s := range []string{
		"claude-sonnet-5", "claude-opus-4-8", "claude-fable-5-1", "claude-3-5-haiku",
		"us.anthropic.claude-sonnet-4-5-v1", "gpt-5.6-luna", "gpt-5.4-mini", "gemini-3.8-flash-low",
		"opencode-go/glm-5.2", "opencode/nemotron-3-ultra-free", "opencode-go/deepseek-v4-flash",
		"kimi-k2.7-code", "qwen3-coder-30b-a3b", "qwen3.5-plus", "muse-spark-1.3", "llama-3.1-70b",
	} {
		if !l.Pattern.MatchString(s) {
			t.Errorf("%q should be model-id-shaped", s)
		}
	}
	for _, s := range []string{
		"sonnet", "haiku", "claude", "claude-config", "claude-sid", "gpt-oss", "gpt-image",
		"qwen-image-2.1", "qwen-image-edit-2511", "qwen3vl_4b_fp8_scaled.safetensors", "flux1", "sdxl",
		"Gemini 3.5 Flash (Medium)", "muse", "codex-sid", "chatgpt-5", "llamacpp",
	} {
		if l.Pattern.MatchString(s) {
			t.Errorf("%q should not be model-id-shaped", s)
		}
	}
}

// Positive and negative controls in one tree: a planted literal is found, and comments,
// tests, testdata, generated files, the registry and an allowed line are not violations.
func TestScanFindsPlantedLiteralAndOnlyThat(t *testing.T) {
	l := pattern(t)
	write(t, l.Root, "mod/feature/f.go", `package feature

// a comment naming gpt-5.6-luna is fine
const planted = "gpt-5.6-luna"

var ok = "sonnet"

// model-id-lint:allow an example in a description
var described = "for example claude-opus-4-8"

var trailing = "gemini-3.8-flash" // model-id-lint:allow a trailing directive
`)
	write(t, l.Root, "mod/feature/f_test.go", "package feature\n\nconst inTest = \"claude-sonnet-5\"\n")
	write(t, l.Root, "mod/feature/testdata/x.go", "package x\n\nconst fixture = \"claude-sonnet-5\"\n")
	write(t, l.Root, "mod/feature/gen.go", "// Code generated by hand. DO NOT EDIT.\n\npackage feature\n\nconst gen = \"claude-sonnet-5\"\n")
	write(t, l.Root, "mod/registry/r.go", "package registry\n\nconst ChatClaude = \"claude-sonnet-5\"\n")
	write(t, l.Root, "mod/table/t.go", "package table\n\n// model-id-lint:allow-file a price table keyed by id\nvar prices = map[string]int{\"claude-opus-4-8\": 5}\n")

	fs, errs := l.Scan("mod")
	if len(errs) != 0 {
		t.Fatal(errs)
	}
	got := statuses(fs)
	want := map[string]Status{
		"mod/feature/f.go:gpt-5.6-luna":                StatusViolation,
		"mod/feature/f.go:for example claude-opus-4-8": StatusAllowed,
		"mod/feature/f.go:gemini-3.8-flash":            StatusAllowed,
		"mod/registry/r.go:claude-sonnet-5":            StatusRegistry,
		"mod/table/t.go:claude-opus-4-8":               StatusFile,
	}
	if len(got) != len(want) {
		t.Errorf("findings = %v, want %v", got, want)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: status %q, want %q (all: %v)", k, got[k], v, got)
		}
	}
}

// An allow without a reason is the silent exemption this lint exists to prevent.
func TestDirectiveNeedsAReason(t *testing.T) {
	l := pattern(t)
	write(t, l.Root, "mod/a.go", "package a\n\n// model-id-lint:allow\nconst x = \"gpt-5.4-mini\"\n")
	fs, errs := l.Scan("mod")
	if len(errs) != 1 || !strings.Contains(errs[0].Error(), "needs a reason") {
		t.Fatalf("errs = %v, want one 'needs a reason'", errs)
	}
	if len(fs) != 1 || fs[0].Status != StatusViolation {
		t.Fatalf("findings = %v, want the literal still a violation", fs)
	}
}

// The real tree passes. Running the linter is CI's job; this keeps `go test` here from
// being green while the tree is red.
func TestRepositoryTreeIsClean(t *testing.T) {
	pat, err := LoadPattern("patterns.txt")
	if err != nil {
		t.Fatal(err)
	}
	l := &Linter{Pattern: pat, Registry: registryFiles, Root: filepath.Join("..", "..")}
	fs, errs := l.Scan(scanDirs...)
	if len(errs) != 0 {
		t.Fatal(errs)
	}
	registry := 0
	for _, f := range fs {
		switch f.Status {
		case StatusViolation:
			t.Errorf("violation: %s", f)
		case StatusRegistry:
			registry++
		}
	}
	// Seeing the registry's own ids proves the walk reached the code at all.
	if registry == 0 {
		t.Error("no registry findings: the scan did not reach workspace/agent/internal/modelfallback")
	}
}
