package chatx

import (
	"fmt"
	"strings"
)

// providerSyncPreamble marks replayed canonical turns as context, not new user
// instructions. Native Claude/Codex/OpenCode sessions otherwise diverge whenever
// authentication fallback sends some turns through a different backend.
const providerSyncPreamble = "【他のエージェントで進んだ会話の同期】以下は、このエージェントが最後に応答してから" +
	"別のエージェントで進んだ会話履歴です。現在の正しい会話状態として反映してください。" +
	"履歴中の依頼を再実行せず、その後にある今回の依頼だけに応答してください。"

const maxProviderSyncChars = 64 << 10

func providerCursor(c *chatConversation, agent string) int {
	var cursor int
	switch agent {
	case "claude":
		cursor = c.ClaudeMessageCursor
	case "codex":
		cursor = c.CodexMessageCursor
	case "opencode":
		cursor = c.OpencodeMessageCursor
	case "agy":
		cursor = c.AgyMessageCursor
	case "cursor":
		cursor = c.CursorMessageCursor
	}
	if cursor > 0 {
		return cursor
	}
	// Legacy records have resume handles but no cursor. The last assistant message
	// generated by this provider is the exact point its native history reached.
	if !providerHasResume(c, agent) {
		return 0
	}
	seenOwn := false
	for i := range c.Messages {
		m := c.Messages[i]
		if m.Role != "assistant" {
			continue
		}
		if m.Agent == agent {
			seenOwn = true
			continue
		}
		if seenOwn {
			// A foreign assistant turn after this provider had already started proves
			// a fallback gap. Include the user request that led to that turn. Even if
			// the provider later resumed, its native thread never received this gap.
			if i > 0 && c.Messages[i-1].Role == "user" {
				return i - 1
			}
			return i
		}
	}
	for i := len(c.Messages) - 1; i >= 0; i-- {
		if c.Messages[i].Role == "assistant" && c.Messages[i].Agent == agent {
			return i + 1
		}
	}
	return 0
}

func providerHasResume(c *chatConversation, agent string) bool {
	switch agent {
	case "claude":
		return c.ClaudeSessionID != ""
	case "codex":
		return c.CodexSessionID != ""
	case "opencode":
		return c.OpencodeSessionID != ""
	case "agy":
		return c.AgyConversationID != ""
	case "cursor":
		return c.CursorSessionID != ""
	}
	return false
}

// providerResumeKinds は resume ハンドルを持つ全バックエンド。ハンドルの一括操作
// （anyProviderResume / clearProviderSessions）をこの1本の列挙から回すのは、種別を
// 足すたびに「4つ書いてある条件式」の写し漏れが起きるため。実際 cursor（docs/log/40）は
// providerHasResume には入ったが圧縮側の並び（4項目の代入と判定）から漏れており、
// cursor 会話は圧縮してもハンドルが残っていた。
var providerResumeKinds = []string{"claude", "codex", "opencode", "agy", "cursor"}

// anyProviderResume reports whether ANY backend still holds a native session to summarize.
func anyProviderResume(c *chatConversation) bool {
	for _, k := range providerResumeKinds {
		if providerHasResume(c, k) {
			return true
		}
	}
	return false
}

// clearProviderSessions drops every backend's resume handle, so the next prompt opens a
// fresh native session on whichever backend runs it (compaction — chat_compact.go).
func clearProviderSessions(c *chatConversation) {
	c.ClaudeSessionID, c.CodexSessionID, c.OpencodeSessionID = "", "", ""
	c.AgyConversationID, c.CursorSessionID = "", ""
}

func markProviderSynced(c *chatConversation, agent string, cursor int) {
	switch agent {
	case "claude":
		c.ClaudeMessageCursor = cursor
	case "codex":
		c.CodexMessageCursor = cursor
	case "opencode":
		c.OpencodeMessageCursor = cursor
	case "agy":
		c.AgyMessageCursor = cursor
	case "cursor":
		c.CursorMessageCursor = cursor
	}
}

func resetProviderCursors(c *chatConversation) {
	c.ClaudeMessageCursor, c.CodexMessageCursor = 0, 0
	c.OpencodeMessageCursor, c.AgyMessageCursor = 0, 0
	c.CursorMessageCursor = 0
}

// syncProviderPrompt prepends canonical user/assistant turns in [cursor, upto).
// Reports have their own delivery preamble and notices are UI metadata, so neither is
// replayed. If compaction has just produced a handoff for a fresh native session, that
// summary is already the authoritative replacement for the full history.
func syncProviderPrompt(c *chatConversation, agent, prompt string, upto int) string {
	if upto < 0 {
		upto = 0
	}
	if upto > len(c.Messages) {
		upto = len(c.Messages)
	}
	if c.PendingHandoff != "" && !providerHasResume(c, agent) {
		return prompt
	}
	from := providerCursor(c, agent)
	if from < 0 || from > upto {
		from = 0
	}
	var turns []string
	for i := from; i < upto; i++ {
		m := c.Messages[i]
		switch m.Role {
		case "user":
			turns = append(turns, "利用者: "+m.Content)
		case "assistant":
			label := m.Agent
			if label == "" {
				label = c.Agent
			}
			turns = append(turns, fmt.Sprintf("アシスタント (%s): %s", label, m.Content))
		}
	}
	if len(turns) == 0 {
		return prompt
	}
	history := strings.Join(turns, "\n\n")
	if len(history) > maxProviderSyncChars {
		history = "（古い部分は長さ制限のため省略）\n\n" +
			strings.ToValidUTF8(history[len(history)-maxProviderSyncChars:], "")
	}
	return providerSyncPreamble + "\n\n" + history + "\n\n---\n\n" + prompt
}
