// The gallery's right-click menu and the "generated by" jump.
//
// Its own file rather than more cases in GalleryView.dom.test.tsx: these mount the same view
// but care about a different axis — the fs write ops it can now reach — and they need the
// clipboard, window.prompt and the confirm dialog stubbed, which the render tests must not be.
//
// What is pinned here is what a screenshot cannot show: that rename sends a path built from
// the FOLDER ON SCREEN (a typed "../x.png" must not walk the picture out of the gallery), that
// delete goes through the shared confirm and not straight to the endpoint, and that the jump
// only appears for a session the list still knows.
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";

interface Entry {
  name: string;
  type: string;
  size?: number;
  mtime?: number;
}

let served: Entry[] = [];
/** Every non-listing request, in order — the fs write ops these tests are about. */
let writes: { url: string; method: string }[] = [];

const fetchMock = vi.fn(async (url: string, opts?: RequestInit) => {
  const u = String(url);
  if (!u.includes("fs/tree")) writes.push({ url: u, method: String(opts?.method || "GET") });
  return {
    ok: true,
    status: 200,
    statusText: "OK",
    headers: { get: () => null },
    text: async () => JSON.stringify({ entries: served }),
    json: async () => ({}),
  } as unknown as Response;
});
vi.stubGlobal("fetch", fetchMock);

const writeText = vi.fn(() => Promise.resolve());
vi.stubGlobal("navigator", Object.assign(globalThis.navigator, { clipboard: { writeText } }));

const { GalleryView } = await import("./GalleryView.tsx");
const { ToastProvider } = await import("../../ui/ToastProvider.tsx");
const { ConfirmProvider } = await import("../../ui/ConfirmProvider.tsx");
const { setLocale } = await import("../../lib/i18n/index.ts");
const { useLayoutStore } = await import("../../layout/store.ts");
const { useWorkspaceStore } = await import("../../core/store/workspace.ts");
const { allViews, freshLayout } = await import("../../layout/ops.ts");
const { useSessionsStore } = await import("../sessions/store.ts");
const { clearGalleryCache } = await import("./galleryCache.ts");

let host: HTMLDivElement;
let root: Root;

const img = (name: string, mtime = 100): Entry => ({ name, type: "file", size: 1000, mtime });

const render = async (path = "gen/uuid-1") => {
  useLayoutStore.getState().openTarget({ content: { kind: "gallery", galleryPath: path } });
  const paneId = allViews(useLayoutStore.getState().layout).find((v) => v.content.kind === "gallery")!.id;
  host = document.createElement("div");
  document.body.appendChild(host);
  root = createRoot(host);
  await act(async () => {
    root.render(
      <ToastProvider>
        <ConfirmProvider>
          <GalleryView paneId={paneId} path={path} />
        </ConfirmProvider>
      </ToastProvider>,
    );
  });
};

const cards = () => [...host.querySelectorAll<HTMLElement>(".gal-card:not(.folder)")];
const folderCards = () => [...host.querySelectorAll<HTMLElement>(".gal-card.folder")];
const menuItems = () => [...document.querySelectorAll<HTMLButtonElement>(".gal-ctxmenu .ui-menu-item")];
const itemFor = (label: string) => menuItems().find((b) => b.textContent?.includes(label));

const rightClick = async (el: HTMLElement) => {
  await act(async () => {
    el.dispatchEvent(new MouseEvent("contextmenu", { bubbles: true, cancelable: true, clientX: 30, clientY: 40 }));
  });
};

/** Right-click the nth image card, the way a pointer does. */
const openMenu = (n = 0) => rightClick(cards()[n]);
/** Right-click the nth FOLDER card — index 0 is "Up" whenever the folder has a parent. */
const openFolderMenu = (n = 0) => rightClick(folderCards()[n]);

const click = async (el: Element | null | undefined) => {
  if (!el) throw new Error("not in the DOM");
  await act(async () => {
    el.dispatchEvent(new MouseEvent("click", { bubbles: true }));
  });
};

beforeEach(() => {
  setLocale("ja"); // these assert on catalogue wording; jsdom's navigator says en-US
  writes = [];
  writeText.mockClear();
  fetchMock.mockClear();
  clearGalleryCache();
  useWorkspaceStore.setState({ state: "running" });
  useLayoutStore.setState({ layout: freshLayout() });
  useSessionsStore.setState({ sessions: [] });
  served = [img("image-1.png"), img("image-2.png", 200)];
});

afterEach(async () => {
  await act(async () => root.unmount());
  document.body.innerHTML = "";
  vi.unstubAllGlobals();
  vi.stubGlobal("fetch", fetchMock);
  vi.stubGlobal("navigator", Object.assign(globalThis.navigator, { clipboard: { writeText } }));
});

describe("ギャラリーの右クリックメニュー", () => {
  it("カードを右クリックすると出て、Escape で閉じる", async () => {
    await render();
    expect(document.querySelector(".gal-ctxmenu")).toBeNull();
    await openMenu();
    expect(document.querySelector(".gal-ctxmenu")).not.toBeNull();
    await act(async () => {
      document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));
    });
    expect(document.querySelector(".gal-ctxmenu")).toBeNull();
  });

  it("パスとファイル名は別の文字列をコピーする", async () => {
    await render();
    await openMenu(); // newest first → image-2.png
    await click(itemFor("パスをコピー"));
    expect(writeText).toHaveBeenLastCalledWith("gen/uuid-1/image-2.png");

    await openMenu();
    await click(itemFor("ファイル名をコピー"));
    expect(writeText).toHaveBeenLastCalledWith("image-2.png");
  });

  it("名前の変更は今のフォルダ配下に送り、一覧を読み直す", async () => {
    vi.stubGlobal("prompt", () => "renamed.png");
    await render();
    await openMenu();
    await click(itemFor("ファイル名を変更"));
    const rename = writes.find((w) => w.url.includes("fs/rename"));
    expect(rename?.method).toBe("POST");
    expect(rename?.url).toContain("from=" + encodeURIComponent("gen/uuid-1/image-2.png"));
    expect(rename?.url).toContain("to=" + encodeURIComponent("gen/uuid-1/renamed.png"));
    // The listing is read again, or the card would keep the old name until the next tick.
    expect(fetchMock.mock.calls.filter((c) => String(c[0]).includes("fs/tree")).length).toBeGreaterThan(1);
  });

  it("スラッシュ入りの名前は送らない（黙って別のフォルダへ移すより断る）", async () => {
    vi.stubGlobal("prompt", () => "../moved.png");
    await render();
    await openMenu();
    await click(itemFor("ファイル名を変更"));
    expect(writes.some((w) => w.url.includes("fs/rename"))).toBe(false);
  });

  it("名前の変更を取り消したら何も送らない", async () => {
    vi.stubGlobal("prompt", () => null);
    await render();
    await openMenu();
    await click(itemFor("ファイル名を変更"));
    expect(writes.some((w) => w.url.includes("fs/rename"))).toBe(false);
  });

  it("削除は確認を挟み、断ったら消さない", async () => {
    await render();
    await openMenu();
    await click(itemFor("ファイルを削除"));
    // The shared confirm is up and nothing has been sent yet.
    expect(document.querySelector(".ui-confirm")).not.toBeNull();
    expect(writes.some((w) => w.url.includes("fs/delete"))).toBe(false);

    const buttons = [...document.querySelectorAll<HTMLButtonElement>(".ui-confirm-actions button")];
    await click(buttons[0]); // cancel
    expect(writes.some((w) => w.url.includes("fs/delete"))).toBe(false);
  });

  it("確認すれば DELETE を送る", async () => {
    await render();
    await openMenu();
    await click(itemFor("ファイルを削除"));
    const buttons = [...document.querySelectorAll<HTMLButtonElement>(".ui-confirm-actions button")];
    await click(buttons[1]); // confirm
    const del = writes.find((w) => w.url.includes("fs/delete"));
    expect(del?.method).toBe("DELETE");
    expect(del?.url).toContain(encodeURIComponent("gen/uuid-1/image-2.png"));
  });
});

describe("生成したセッションへ飛ぶ", () => {
  const session = { name: "s1", kind: "claude", title: "絵を描く", alive: true, generatedImagesPath: "gen/uuid-1" };

  it("セッション一覧が知らないフォルダでは出さない（行き先の無いボタンを置かない）", async () => {
    await render();
    expect(host.querySelector(".gal-madeby")).toBeNull();
    await openMenu();
    expect(itemFor("を開く")).toBeUndefined();
  });

  it("このフォルダを生成したセッションの名前を出し、押すとそのセッションを開く", async () => {
    useSessionsStore.setState({ sessions: [session as never] });
    await render();
    const go = host.querySelector<HTMLButtonElement>(".gal-madeby");
    expect(go?.textContent).toContain("絵を描く");

    await click(go);
    // Where a rail row leads for a live chat-capable kind: the mirror, on this session.
    const opened = allViews(useLayoutStore.getState().layout).find((v) => v.content.kind === "terminal");
    expect(opened?.session).toBe("s1");
  });

  it("右クリックメニューからも同じ場所へ飛べる", async () => {
    useSessionsStore.setState({ sessions: [session as never] });
    await render();
    await openMenu();
    await click(itemFor("絵を描く"));
    expect(document.querySelector(".gal-ctxmenu")).toBeNull();
    const opened = allViews(useLayoutStore.getState().layout).find((v) => v.content.kind === "terminal");
    expect(opened?.session).toBe("s1");
  });
});

describe("フォルダカードの右クリックメニュー", () => {
  beforeEach(() => {
    served = [img("image-1.png"), { name: "uuid-2", type: "dir" }];
  });

  it("「上へ」には出さない（出ていく先を消す操作はここに要らない）", async () => {
    await render(); // "gen/uuid-1" has a parent, so the first folder card is "Up"
    const up = folderCards()[0];
    expect(up.querySelector(".gal-name")?.textContent).toBe("上へ");
    await rightClick(up);
    expect(document.querySelector(".gal-ctxmenu")).toBeNull();
  });

  it("フォルダ用の文言で出て、パスとフォルダ名をコピーできる", async () => {
    await render();
    await openFolderMenu(1); // 0 is "Up"
    expect(itemFor("フォルダ名をコピー")).toBeDefined();
    expect(itemFor("フォルダ名を変更")).toBeDefined();
    expect(itemFor("フォルダを削除")).toBeDefined();

    await click(itemFor("パスをコピー"));
    expect(writeText).toHaveBeenLastCalledWith("gen/uuid-1/uuid-2");
    await openFolderMenu(1);
    await click(itemFor("フォルダ名をコピー"));
    expect(writeText).toHaveBeenLastCalledWith("uuid-2");
  });

  it("フォルダの削除は「中身ごと」と断ってから DELETE を送る", async () => {
    await render();
    await openFolderMenu(1);
    await click(itemFor("フォルダを削除"));
    expect(document.querySelector(".ui-confirm-body")?.textContent).toContain("中身ごと");
    const buttons = [...document.querySelectorAll<HTMLButtonElement>(".ui-confirm-actions button")];
    await click(buttons[1]);
    const del = writes.find((w) => w.url.includes("fs/delete"));
    expect(del?.method).toBe("DELETE");
    expect(del?.url).toContain(encodeURIComponent("gen/uuid-1/uuid-2"));
  });

  it("フォルダの名前の変更も今のフォルダ配下に送る", async () => {
    vi.stubGlobal("prompt", () => "renamed");
    await render();
    await openFolderMenu(1);
    await click(itemFor("フォルダ名を変更"));
    const rename = writes.find((w) => w.url.includes("fs/rename"));
    expect(rename?.url).toContain("from=" + encodeURIComponent("gen/uuid-1/uuid-2"));
    expect(rename?.url).toContain("to=" + encodeURIComponent("gen/uuid-1/renamed"));
  });

  it("そのフォルダ自身を生成したセッションへ飛べる（一覧のフォルダは UUID で中身を語らない）", async () => {
    useSessionsStore.setState({
      sessions: [{ name: "s2", kind: "claude", title: "夜の絵", alive: true, generatedImagesPath: "gen/uuid-1/uuid-2" } as never],
    });
    await render();
    await openFolderMenu(1);
    await click(itemFor("夜の絵"));
    const opened = allViews(useLayoutStore.getState().layout).find((v) => v.content.kind === "terminal");
    expect(opened?.session).toBe("s2");
  });
});
