// openGallery — the one way in to the image gallery (ADR 0080). Every entry point the
// ADR lists (a folder's context menu, an image's context menu, the viewer header, a
// session's menu, the shared lightbox bar) calls this and nothing else, so the opening
// convention lives here instead of being re-decided per menu.
//
// The convention is the Console's existing one: a plain click reuses the current pane,
// Ctrl/⌘ and the middle button open a second one. On a phone there is no "beside", and
// the layout store already folds "open in a new pane" back into the current one there
// (mobileMatches in layout/store), so a caller never has to ask.
//
// Its own module, apart from the view, because the menus that call it are mounted
// everywhere: importing GalleryView from a left-rail menu would pull the grid, its CSS
// and the fs client into every one of those bundles.
import { useLayoutStore } from "../../layout/store.ts";
import { allViews } from "../../layout/ops.ts";
import type { PaneContent } from "../../layout/types.ts";

export interface OpenGalleryOptions {
  /** Image to enlarge on arrival: a file name, or a browse-root-relative path. */
  focus?: string;
  /**
   * Session the pictures were generated by, as its NAME (the slug: `[A-Za-z0-9_-]{1,40}`),
   * not its display title. The pane resolves the title from the name every render, so a
   * renamed session keeps a correct tab — and a display name passed here is dropped
   * outright by the stored-layout validator, which takes the title away on the next
   * reload. Used for the tab title only; it targets nothing.
   */
  session?: string;
  /** Ctrl/⌘-click or middle click: open beside instead of in the current pane. */
  newPane?: boolean;
}

/**
 * Open `path` (a browse-root-relative FOLDER) as a gallery pane.
 *
 * A gallery of the same folder that is already on screen is RETARGETED in place rather
 * than opened again: sameTarget dedupes on the folder alone (layout/ops.ts), so a second
 * open carrying a different `focus` would otherwise activate that pane and silently drop
 * the image the reader asked for — the same trap openFileMode documents for `mode`.
 */
export function openGallery(path: string, opts: OpenGalleryOptions = {}): void {
  if (!path) return;
  const content: PaneContent = {
    kind: "gallery",
    galleryPath: path,
    ...(opts.focus ? { galleryFocus: opts.focus } : {}),
    ...(opts.session ? { gallerySession: opts.session } : {}),
  };
  const st = useLayoutStore.getState();
  const existing = allViews(st.layout).find((p) => p.content.kind === "gallery" && p.content.galleryPath === path);
  if (existing && !opts.newPane) {
    st.setPaneTarget(existing.id, { content });
    st.selectTab(existing.id);
    return;
  }
  if (opts.newPane) st.openTargetInNew({ content });
  else st.openTarget({ content });
}
