// English カタログ / ドメイン: chat
// キー接頭辞: chat
//
// ⚠️ 追記は**自分のドメインのファイルだけ**に行う（ADR 0067 決定 4）。分割前は 4,700 行の
// 1 ファイルで、フロントの並列セッションが全員ここへ追記＝毎回確実に衝突していた。
// ja が正本。Record<keyof typeof ja...> で ja に無いキー / 足りないキーを tsc が落とす。
import type { chat as jaChat } from "../ja/chat.ts";

export const chat: Record<keyof typeof jaChat, string> = {
  // === P2 ChatView (features/chat/ChatView.tsx) ===
  "chat.not_found": "Conversation not found",
  "chat.load_failed": "Failed to load the conversation",
  "chat.new_title": "New chat",
  "chat.create_failed": "Failed to create the conversation",
  "chat.image_paste_failed": "Failed to paste the image",
  "chat.image_paste_failed_net": "Failed to paste the image (network error)",
  "chat.label": "Chat",
  "chat.tts_source_work": "Chat · working steps",
  "chat.state_running": "Working",
  "chat.compact_btn": "Compact",
  "chat.compact_tip": "Summarize the conversation and hand only the summary to a fresh session to shrink context (this view keeps the full history)",
  "chat.compact_confirm_title": "Compact the context?",
  "chat.compact_confirm_body":
    "The conversation is summarized and only that summary is handed to a fresh session. The history in this view is kept as is, but only the summary carries over. Producing the summary costs one turn of tokens.",
  "chat.compacting": "Compacting…",
  "chat.compact_failed": "Failed to compact the context.",
  "chat.switch_agent": "Switch agent",
  "chat.switch_agent_tip": "Switch the agent (CLI) that runs this conversation",
  "chat.switch_agent_note":
    "The history so far is handed over with your next message (that one turn costs extra tokens). The model is re-resolved from each CLI's row in Settings > Assistant.",
  "chat.switch_agent_failed": "Failed to switch the agent.",
  "chat.switch_agent_offline": "This CLI is not connected (sign in under Settings > Connections to select it).",
  "chat.state_idle": "Idle",
  "chat.assistant_fallback": "Assistant",
  "chat.greeting_empty": "Send a message to start the conversation.",
  "chat.empty_hint":
    "Send a message to start the conversation. You can ask it to translate or summarize a Markdown document, answer questions, and more.",
  "chat.you": "You",
  "chat.report_role": "Session report",
  // Session-report card (docs/log/28 P6). The card carries the FACTS only; the operator's
  // marching orders are generated by the Agent when it builds the prompt, never stored.
  // {display}/{name} name the reporting session; the rest are arguments from the Agent.
  // features/chat/report.ts assembles these.
  "chat.report.headline": "Report from session “{display}” ({name}): ",
  "chat.report.answer_ready": "The session answered and is now waiting for input.",
  "chat.report.turn_failed":
    "The turn ended with an error on the model/provider side and the session is back to waiting for input (no answer was generated).",
  "chat.report.turn_aborted":
    "The turn was cut off and the session is back to waiting for input (a dropped connection, a temporary rate limit — something that clears on its own; the answer is unfinished). Re-sending resumes it from where it stopped.",
  "chat.report.turn_aborted_capped":
    "The turn was cut off and the session is back to waiting for input (a dropped connection, a temporary rate limit — something that clears on its own; the answer is unfinished). Re-sending resumes it from where it stopped. [The automatic-resume limit ({max}) has been reached]",
  "chat.report.question": "The session has stopped, presenting a question (a set of choices).",
  "chat.report.plan_approval": "The session has stopped, presenting a plan and waiting for approval.",
  "chat.report.permission_request":
    "The session has stopped, waiting for permission to run a tool. Permission has to be granted from the Console.",
  "chat.report.reopened": "The completion reported earlier was premature — the session has gone on working since.",
  "chat.report.reopen_capped":
    "The completion reported earlier was premature, and the completion verdict keeps oscillating (the correction limit of {max} has been reached, so there will be no further automatic corrections).",
  "chat.report.exit": "The agent process exited abnormally: {label}.",
  "chat.report.unknown": "The state changed ({kind}).",
  "chat.report.exit_reason.oom": "OOM (killed — out of memory)",
  "chat.report.exit_reason.crashed": "crashed",
  "chat.report.exit_reason.killed": "force-killed (SIGKILL)",
  "chat.report.note.rate_limit_resume":
    "[Stopped by the usage limit] An automatic resume is booked for {at} (when the limit lifts), which will send this session a nudge to continue.",
  "chat.report.note.fold": "(This report is the completion of {count} instructions. Dispatched: {ats})",
  "chat.report.note.reopen_target": "(correcting the completion report of {at})",
  "chat.notice.ctx_pressure":
    "This conversation has reached about {pct}% of its context limit ({tokens} / {window} tokens). Going further degrades answer quality, makes turns fail and burns more tokens. Use “Compact” at the right of the context bar in the header to carry only a summary into a fresh session, or start a new chat at a natural break.",
  "chat.notice.ctx_overflow":
    "The context limit was exceeded, so no reply could be generated. This conversation cannot continue as it is. Use “Compact” at the right of the context bar in the header to carry only a summary into a fresh session, or open a new chat and hand over just the points you still need.",
  "chat.notice.auto_paused.head": "Automatic replies paused: the limit of {limit} consecutive turns was reached.",
  "chat.notice.auto_paused.pending_one": " {count} session report is still unprocessed.",
  "chat.notice.auto_paused.pending_other": " {count} session reports are still unprocessed.",
  "chat.notice.auto_paused.tail":
    " To continue, send a message in this chat (e.g. “go on”). The next message resets the automatic-reply count and carries the pending reports over.",
  "chat.notice.compact_manual":
    "Context compacted. Only the summary below is carried into a fresh session, and the conversation continues on top of it (the history in this view stays as it is).\n\n---\n\n{summary}",
  "chat.notice.compact_auto":
    "Context usage crossed the threshold, so it was compacted automatically. Only the summary below is carried into a fresh session, and the conversation continues on top of it (the history in this view stays as it is).\n\n---\n\n{summary}",
  "chat.notice.compact_recovery":
    "Compacted to recover automatically from a context-overflow error. Only the summary below is carried into a fresh session, and the conversation continues on top of it (the history in this view stays as it is).\n\n---\n\n{summary}",
  "chat.notice.agent_switched":
    "This conversation switched to “{agent}”. From here on {agent} answers. The history so far is handed over with your next message, so that first turn costs extra tokens. The model was re-resolved from the {agent} row in Settings > Assistant.",
  "chat.notice.plan_updated":
    "Work plan updated. It is carried into every new session verbatim — never summarized.\n\n---\n\n{plan}",
  "chat.plan.title": "Work plan",
  "chat.plan.toggle_tip": "Open the work plan (carried into new sessions verbatim, never summarized by compaction)",
  "chat.plan.edit": "Edit",
  "chat.plan.refresh": "Refresh",
  "chat.plan.refreshing": "Refreshing…",
  "chat.plan.refresh_tip": "Re-derive the plan from the recent conversation (press right after the plan changed in discussion)",
  "chat.plan.clear": "Clear",
  "chat.plan.clear_confirm_title": "Clear the work plan?",
  "chat.plan.clear_confirm_body":
    "Empties this conversation's work plan, so nothing is carried into new sessions any more (the message history and the handoff summary stay as they are).",
  "chat.plan.placeholder": "## Constraints\n## Given\n## Next up",
  "chat.plan.empty": "No plan yet. Use Refresh to derive one from the recent conversation, or Edit to write it yourself.",
  "chat.plan.note":
    "The plan is carried into every new session verbatim, never summarized. Compaction keeps it up to date with the recent conversation.",
  "chat.plan.failed": "Failed to update the work plan",
  "chat.working": "Working…",
  "chat.thinking": "Thinking…",
  "chat.suggest_ai": "Suggest replies with AI (from the recent conversation)",
  "chat.suggest_none": "Couldn't suggest replies (too little conversation, or no AI backend available)",
  "chat.suggest_failed": "Failed to generate reply suggestions",
  "chat.remove": "Remove",
  "chat.uploading": "Uploading…",
  "chat.stop": "Stop",
  "chat.send": "Send",
  "chat.prev_input": "Previous input",
  "chat.next_input": "Next input",
  "chat.work_process": "Working steps",
  "chat.tool_count_one": "{count} tool",
  "chat.tool_count_other": "{count} tools",
  "chat.interim_count_one": " · {count} interim reply",
  "chat.interim_count_other": " · {count} interim replies",
  "chat.read_from_here": "Read from here",
  "chat.read_title": "Read aloud (karaoke)",
  "chat.read": "Read aloud",
  "chat.pause": "Pause",
  "chat.resume": "Resume",
  "chat.copy_md_title": "Copy Markdown",
  "chat.copied": "Copied",
  "chat.copy": "Copy",
  "chat.preview_failed": "Couldn't load the preview",
  "chat.click_to_zoom": "Click to enlarge",
  "chat.pasted_image_alt": "Pasted image",
  "chat.ph_mod_img": "Type a message (Ctrl+Enter to send / Enter for newline / paste to attach an image)",
  "chat.ph_enter_img": "Type a message (Enter to send / Shift+Enter for newline / paste to attach an image)",
  "chat.ph_mod": "Type a message (Ctrl+Enter to send / Enter for newline)",
  "chat.ph_enter": "Type a message (Enter to send / Shift+Enter for newline)",
  "chat.ph_loading": "Loading…",
  "chat.intro": "Send session notifications to Discord / Slack. Toggle notifications on/off in Personal › Notifications.",
  "chat.settings": "Notification settings",
};
