// enkana_dict.go — 英語カタカナ読み(enkana.go)のオーバーライド辞書。AWS サービス名や
// 開発者ジャルゴンは CMU 発音辞書では網羅できない/慣用読みと違うため、ここで手当てする。
// convertWord/convertToken が CMUdict より優先して引く。キーは小文字。慣用の日本語読みを
// 採用（例 json→ジェイソン, dao→ダオ）。**足りない語はここに 1 行足すだけで拡張できる。**
//
// 網羅は限定的（数百語規模の手キュレーション）。EC2/S3 のような略語＋数字は enkana.go の
// ルールが自動処理するので、原則ここには単語系を置く。
package main

var techKana = map[string]string{
	// --- 開発ジャルゴン / 一般 ---
	"dao":        "ダオ",
	"json":       "ジェイソン",
	"yaml":       "ヤムル",
	"yml":        "ヤムル",
	"toml":       "トムル",
	"sql":        "エスキューエル",
	"nosql":      "ノーエスキューエル",
	"graphql":    "グラフキューエル",
	"grpc":       "ジーアールピーシー",
	"api":        "エーピーアイ",
	"rest":       "レスト",
	"url":        "ユーアールエル",
	"uri":        "ユーアールアイ",
	"id":         "アイディー", // CMUdict は /ɪd/（イド）で引いてしまうため明示
	"uuid":       "ユーユーアイディー",
	"ipv4":       "アイピーブイフォー",
	"ipv6":       "アイピーブイシックス",
	"cli":        "シーエルアイ",
	"gui":        "グーイ",
	"oauth":      "オーオース",
	"origin":     "オリジン",
	"repo":       "レポ",
	"repos":      "レポズ",
	"jwt":        "ジェイダブリューティー",
	"regex":      "レジェックス",
	"enum":       "イーナム",
	"async":      "エイシンク",
	"await":      "アウェイト",
	"middleware": "ミドルウェア",
	"webhook":    "ウェブフック",
	"env":        "エンブ",
	"stdout":     "スタンダードアウト",
	"stderr":     "スタンダードエラー",
	// --- 言語 / ランタイム ---
	"golang":     "ゴーラン",
	"kotlin":     "コトリン",
	"typescript": "タイプスクリプト",
	"javascript": "ジャバスクリプト",
	"nodejs":     "ノードジェイエス",
	"deno":       "ディーノ",
	"php":        "ピーエイチピー",
	"csharp":     "シーシャープ",
	// --- ミドルウェア / ツール ---
	"nginx":      "エンジンエックス",
	"redis":      "レディス",
	"kafka":      "カフカ",
	"postgres":   "ポストグレス",
	"postgresql": "ポストグレスキューエル",
	"mysql":      "マイエスキューエル",
	"sqlite":     "エスキューライト",
	"mongodb":    "モンゴディービー",
	"docker":     "ドッカー",
	"kubernetes": "クーバネティス",
	"k8s":        "ケーエイツエス",
	"terraform":  "テラフォーム",
	"ansible":    "アンシブル",
	"grafana":    "グラファナ",
	"prometheus": "プロメテウス",
	"kibana":     "キバナ",
	"jenkins":    "ジェンキンス",
	"gradle":     "グレイドル",
	"maven":      "メイブン",
	"webpack":    "ウェブパック",
	"vite":       "ヴィート",
	"eslint":     "イーエスリント",
	// --- AWS サービス（略語系は EC2/S3 等ルールで自動、ここは語形の慣用読み） ---
	"aws":            "エーダブリューエス",
	"lambda":         "ラムダ",
	"dynamodb":       "ダイナモディービー",
	"cloudfront":     "クラウドフロント",
	"cloudwatch":     "クラウドウォッチ",
	"cloudformation": "クラウドフォーメーション",
	"fargate":        "ファーゲート",
	"cognito":        "コグニート",
	"athena":         "アテナ",
	"redshift":       "レッドシフト",
	"aurora":         "オーロラ",
	"kinesis":        "キネシス",
	"route":          "ルート",
	"route53":        "ルートゴジュウサン",
	"iam":            "アイアム",
	"vpc":            "ブイピーシー",
	"ecs":            "イーシーエス",
	"eks":            "イーケーエス",
	"ecr":            "イーシーアール",
	"rds":            "アールディーエス",
	"sqs":            "エスキューエス",
	"sns":            "エスエヌエス",
	"ssm":            "エスエスエム",
	"efs":            "イーエフエス",
	"ebs":            "イービーエス",
	"kms":            "ケーエムエス",
	"acm":            "エーシーエム",
	"elb":            "イーエルビー",
	"asg":            "エーエスジー",
	"amplify":        "アンプリファイ",
	"bedrock":        "ベッドロック",
	// --- クラウド / ホスティング ---
	"azure":        "アジュール",
	"gcp":          "ジーシーピー",
	"firebase":     "ファイアベース",
	"vercel":       "ヴァーセル",
	"netlify":      "ネットリファイ",
	"cloudflare":   "クラウドフレア",
	"heroku":       "ヘロク",
	"supabase":     "スーパーベース",
	"digitalocean": "デジタルオーシャン",
	// --- SaaS / サービス / ブランド ---
	"google":     "グーグル",
	"wikipedia":  "ウィキペディア",
	"gmail":      "ジーメール",
	"chrome":     "クローム",
	"slack":      "スラック",
	"teams":      "チームズ",
	"zoom":       "ズーム",
	"excel":      "エクセル",
	"word":       "ワード",
	"powerpoint": "パワーポイント",
	"outlook":    "アウトルック",
	"onedrive":   "ワンドライブ",
	"sharepoint": "シェアポイント",
	"office":     "オフィス",
	"figma":      "フィグマ",
	"adobe":      "アドビ",
	"photoshop":  "フォトショップ",
	"github":     "ギットハブ",
	"gitlab":     "ギットラボ",
	"bitbucket":  "ビットバケット",
	"jira":       "ジラ",
	"confluence": "コンフルエンス",
	"atlassian":  "アトラシアン",
	"notion":     "ノーション",
	"trello":     "トレロ",
	"asana":      "アサナ",
	"linear":     "リニア",
	"claude":     "クロード",
	"chatgpt":    "チャットジーピーティー",
	"openai":     "オープンエーアイ",
	"anthropic":  "アンスロピック",
	"gemini":     "ジェミニ",
	"copilot":    "コパイロット",
	"cursor":     "カーサー",
	"datadog":    "データドッグ",
	"sentry":     "セントリー",
	"twilio":     "トゥイリオ",
	"stripe":     "ストライプ",
	"postman":    "ポストマン",
	"vscode":     "ブイエスコード",
	"intellij":   "インテリジェイ",
	"npm":        "エヌピーエム",
	"pnpm":       "ピーエヌピーエム",
	// --- フレームワーク / ライブラリ / テスト ---
	"react":         "リアクト",
	"nextjs":        "ネクストジェイエス",
	"vue":           "ビュー",
	"angular":       "アンギュラー",
	"svelte":        "スベルト",
	"tailwind":      "テイルウィンド",
	"jest":          "ジェスト",
	"vitest":        "ヴィテスト",
	"cypress":       "サイプレス",
	"playwright":    "プレイライト",
	"swagger":       "スワッガー",
	"openapi":       "オープンエーピーアイ",
	"helm":          "ヘルム",
	"elasticsearch": "エラスティックサーチ",
	"rabbitmq":      "ラビットエムキュー",
	// --- 過去セッションのコーパスから抽出した未カバー語（docs/24）。実際に読み上げ対象の
	//     回答テキストに頻出しながら CMUdict に無く「綴りママ/英字読み止まり」だった一般的な
	//     開発語・外部プロダクト名・小文字略語を手当て。抽出手順は enkana_freq の突合スキャン。 ---
	// 開発語（複合語・派生語は camelCase 分割が効かず綴りママになるため明示）
	"config":       "コンフィグ",
	"runtime":      "ランタイム",
	"refactor":     "リファクター",
	"grep":         "グレップ",
	"tmux":         "ティーマックス",
	"worktree":     "ワークツリー",
	"subagent":     "サブエージェント",
	"handoff":      "ハンドオフ",
	"readme":       "リードミー",
	"typecheck":    "タイプチェック",
	"struct":       "ストラクト",
	"mutex":        "ミューテックス",
	"entrypoint":   "エントリーポイント",
	"filepath":     "ファイルパス",
	"timestamp":    "タイムスタンプ",
	"changelog":    "チェンジログ",
	"allowlist":    "アローリスト",
	"localstorage": "ローカルストレージ",
	"stdin":        "スタンダードイン", // 既存 stdout=スタンダードアウト / stderr=スタンダードエラー に揃える
	// UI 語
	"placeholder": "プレースホルダー",
	"popover":     "ポップオーバー",
	"tooltip":     "ツールチップ",
	"dropdown":    "ドロップダウン",
	"viewport":    "ビューポート",
	"frontend":    "フロントエンド",
	"websocket":   "ウェブソケット",
	"dockerfile":  "ドッカーファイル",
	"gzip":        "ジージップ",
	// 外部プロダクト / ツール名
	"opencode": "オープンコード",
	"codex":    "コーデックス",
	"ollama":   "オラマ",
	"voicevox": "ボイスボックス",
	"zundamon": "ずんだもん",
	"marp":     "マープ",
	"xterm":    "エックスターム",
	// 小文字で書かれる略語（大文字なら spellLetters が拾うが、小文字は綴りママになるため明示）
	"mcp": "エムシーピー",
	"llm": "エルエルエム",
	"sdk": "エスディーケー",
	"css": "シーエスエス",
	"svg": "エスブイジー",
	"jsx": "ジェイエスエックス",
	"tsx": "ティーエスエックス",
	"tsc": "ティーエスシー",
	"scm": "エスシーエム",
	"lfs": "エルエフエス",
	"tui": "ティーユーアイ",
	"sso": "エスエスオー",
	"ssh": "エスエスエイチ",
	"tls": "ティーエルエス",
	"jvm": "ジェイブイエム",
	"png": "ピーエヌジー",
	"poc": "ピーオーシー",
	"mvp": "エムブイピー",
	"rtk": "アールティーケー",
}
