// enkana_dict.go — 英語カタカナ読み(enkana.go)のオーバーライド辞書。AWS サービス名や
// 開発者ジャルゴンは CMU 発音辞書では網羅できない/慣用読みと違うため、ここで手当てする。
// convertWord/convertToken が CMUdict より優先して引く。キーは小文字。慣用の日本語読みを
// 採用（例 json→ジェイソン, dao→ダオ）。**足りない語はここに 1 行足すだけで拡張できる。**
//
// 網羅は限定的（数百語規模の手キュレーション）。EC2/S3 のような略語＋数字は enkana.go の
// ルールが自動処理するので、原則ここには単語系を置く。
package main

var techKana = map[string]string{
	// --- 開発ジャルゴン / 一般 ---
	"dom":        "ドム",     // CMUdict は実在語 dom→"ダム"。DOM(Document Object Model) は慣用でドム
	"good":       "グッド",    // CMUdict は末尾 D が促音化せず "グド" になる（実機フィードバック）
	"well":       "ウェル",    // 変異形で "ウェルル" になるとの報告あり。慣用読みに固定
	"agent":      "エージェント", // CMUdict は "エイジャント" 寄りに誤読（実機フィードバック）
	"manage":     "マネージ",   // manage 系は CMUdict だと "マナジ..." になる（長音が落ちる）
	"managed":    "マネージド",  // 実機フィードバック（例: "マネージドサービス"）
	"manager":    "マネージャー",
	"managers":   "マネージャーズ",
	"management": "マネジメント", // この語だけ慣用的に長音無し（マネージメントでなく）
	"image":      "イメージ",   // CMUdict は "イマジ" と誤読（実機フィードバック）
	"images":     "イメージズ",  // Docker images 等
	"imaging":    "イメージング",
	"dao":        "ダオ",
	"json":       "ジェイソン",
	"yaml":       "ヤムル",
	"yml":        "ヤムル",
	"toml":       "トムル",
	"sql":        "エスキューエル",
	"nosql":      "ノーエスキューエル",
	"graphql":    "グラフキューエル",
	"grpc":       "ジーアールピーシー",
	"api":        "エーピーアイ",
	"rest":       "レスト",
	"url":        "ユーアールエル",
	"uri":        "ユーアールアイ",
	"id":         "アイディー", // CMUdict は /ɪd/（イド）で引いてしまうため明示
	"uuid":       "ユーユーアイディー",
	"ipv4":       "アイピーブイフォー",
	"ipv6":       "アイピーブイシックス",
	"cli":        "シーエルアイ",
	"gui":        "グーイ",
	"oauth":      "オーオース",
	"origin":     "オリジン",
	"body":       "ボディ",
	"query":      "クエリ",
	"parameter":  "パラメータ",
	"iframe":     "アイフレーム",
	"preview":    "プレビュー",
	"cookie":     "クッキー",
	"httpapi":    "エイチティーティーピーエーピーアイ",
	"repo":       "レポ",
	"repos":      "レポズ",
	"jwt":        "ジェイダブリューティー",
	"regex":      "レジェックス",
	"enum":       "イーナム",
	"async":      "エイシンク",
	"await":      "アウェイト",
	"middleware": "ミドルウェア",
	"webhook":    "ウェブフック",
	"env":        "エンブ",
	"stdout":     "スタンダードアウト",
	"stderr":     "スタンダードエラー",
	// --- 言語 / ランタイム ---
	"golang":     "ゴーラン",
	"kotlin":     "コトリン",
	"typescript": "タイプスクリプト",
	"javascript": "ジャバスクリプト",
	"nodejs":     "ノードジェイエス",
	"deno":       "ディーノ",
	"php":        "ピーエイチピー",
	"csharp":     "シーシャープ",
	// --- ミドルウェア / ツール ---
	"nginx":      "エンジンエックス",
	"redis":      "レディス",
	"kafka":      "カフカ",
	"postgres":   "ポストグレス",
	"postgresql": "ポストグレスキューエル",
	"mysql":      "マイエスキューエル",
	"sqlite":     "エスキューライト",
	"mongodb":    "モンゴディービー",
	"docker":     "ドッカー",
	"kubernetes": "クーバネティス",
	"k8s":        "ケーエイツエス",
	"terraform":  "テラフォーム",
	"ansible":    "アンシブル",
	"grafana":    "グラファナ",
	"prometheus": "プロメテウス",
	"kibana":     "キバナ",
	"jenkins":    "ジェンキンス",
	"gradle":     "グレイドル",
	"maven":      "メイブン",
	"webpack":    "ウェブパック",
	"vite":       "ヴィート",
	"eslint":     "イーエスリント",
	// --- AWS サービス（略語系は EC2/S3 等ルールで自動、ここは語形の慣用読み） ---
	"aws":            "エーダブリューエス",
	"lambda":         "ラムダ",
	"dynamodb":       "ダイナモディービー",
	"cloudfront":     "クラウドフロント",
	"cloudwatch":     "クラウドウォッチ",
	"cloudformation": "クラウドフォーメーション",
	"fargate":        "ファーゲート",
	"cognito":        "コグニート",
	"athena":         "アテナ",
	"redshift":       "レッドシフト",
	"aurora":         "オーロラ",
	"kinesis":        "キネシス",
	"route":          "ルート",
	"route53":        "ルートゴジュウサン",
	"iam":            "アイアム",
	"vpc":            "ブイピーシー",
	"ecs":            "イーシーエス",
	"eks":            "イーケーエス",
	"ecr":            "イーシーアール",
	"rds":            "アールディーエス",
	"sqs":            "エスキューエス",
	"sns":            "エスエヌエス",
	"ssm":            "エスエスエム",
	"efs":            "イーエフエス",
	"ebs":            "イービーエス",
	"kms":            "ケーエムエス",
	"acm":            "エーシーエム",
	"elb":            "イーエルビー",
	"asg":            "エーエスジー",
	"amplify":        "アンプリファイ",
	"bedrock":        "ベッドロック",
	// --- クラウド / ホスティング ---
	"azure":        "アジュール",
	"gcp":          "ジーシーピー",
	"firebase":     "ファイアベース",
	"vercel":       "ヴァーセル",
	"netlify":      "ネットリファイ",
	"cloudflare":   "クラウドフレア",
	"heroku":       "ヘロク",
	"supabase":     "スーパーベース",
	"digitalocean": "デジタルオーシャン",
	// --- SaaS / サービス / ブランド ---
	"google":      "グーグル",
	"wikipedia":   "ウィキペディア",
	"gmail":       "ジーメール",
	"chrome":      "クローム",
	"slack":       "スラック",
	"teams":       "チームズ",
	"zoom":        "ズーム",
	"excel":       "エクセル",
	"word":        "ワード",
	"powerpoint":  "パワーポイント",
	"outlook":     "アウトルック",
	"onedrive":    "ワンドライブ",
	"sharepoint":  "シェアポイント",
	"office":      "オフィス",
	"figma":       "フィグマ",
	"adobe":       "アドビ",
	"photoshop":   "フォトショップ",
	"github":      "ギットハブ",
	"gitlab":      "ギットラボ",
	"bitbucket":   "ビットバケット",
	"jira":        "ジラ",
	"confluence":  "コンフルエンス",
	"atlassian":   "アトラシアン",
	"notion":      "ノーション",
	"trello":      "トレロ",
	"asana":       "アサナ",
	"linear":      "リニア",
	"kintone":     "キントーン",
	"nexmo":       "ネクスモ",
	"sinch":       "シンチ",
	"citic":       "シティック",
	"softbank":    "ソフトバンク", // 全大文字 SOFTBANK は 5 字超で英字名読みルールから漏れるため明示
	"rakuten":     "ラクテン",
	"docomo":      "ドコモ",
	"au":          "エーユー", // キャリアの au（裸 URL は読み上げ前に除去済みなので .au ドメインとは衝突しない）
	"ymobile":     "ワイモバイル",
	"dena":        "ディーエヌエー", // DeNA は camelCase 分割で De/NA に割れて崩れるため明示
	"gree":        "グリー",
	"sybase":      "サイベース",
	"twiml":       "トゥイムル",
	"8x8":         "エイトバイエイト", // 数字入りキーは全トークン一致で引かれる（ipv4/route53 と同じ）
	"vonage":      "ボネージ",
	"plivo":       "プリボ",
	"messagebird": "メッセージバード",
	"sendgrid":    "センドグリッド",
	"webrtc":      "ウェブアールティーシー",
	"volte":       "ボルテ",
	"freeswitch":  "フリースイッチ",
	"cisco":       "シスコ",
	"ericsson":    "エリクソン",
	"nokia":       "ノキア",
	"huawei":      "ファーウェイ",
	"qualcomm":    "クアルコム",
	"claude":      "クロード",
	"chatgpt":     "チャットジーピーティー",
	"openai":      "オープンエーアイ",
	"anthropic":   "アンスロピック",
	"gemini":      "ジェミニ",
	"copilot":     "コパイロット",
	"cursor":      "カーサー",
	"kiro":        "キロ",
	"datadog":     "データドッグ",
	"sentry":      "セントリー",
	"twilio":      "トゥイリオ",
	"stripe":      "ストライプ",
	"postman":     "ポストマン",
	"vscode":      "ブイエスコード",
	"intellij":    "インテリジェイ",
	"npm":         "エヌピーエム",
	"pnpm":        "ピーエヌピーエム",
	// --- フレームワーク / ライブラリ / テスト ---
	"react":         "リアクト",
	"nextjs":        "ネクストジェイエス",
	"vue":           "ビュー",
	"angular":       "アンギュラー",
	"svelte":        "スベルト",
	"tailwind":      "テイルウィンド",
	"jest":          "ジェスト",
	"vitest":        "ヴィテスト",
	"cypress":       "サイプレス",
	"playwright":    "プレイライト",
	"swagger":       "スワッガー",
	"openapi":       "オープンエーピーアイ",
	"helm":          "ヘルム",
	"elasticsearch": "エラスティックサーチ",
	"rabbitmq":      "ラビットエムキュー",
	// --- 過去セッションのコーパスから抽出した未カバー語（docs/log/24）。実際に読み上げ対象の
	//     回答テキストに頻出しながら CMUdict に無く「綴りママ/英字読み止まり」だった一般的な
	//     開発語・外部プロダクト名・小文字略語を手当て。抽出手順は enkana_freq の突合スキャン。 ---
	// 開発語（複合語・派生語は camelCase 分割が効かず綴りママになるため明示）
	"config":       "コンフィグ",
	"runtime":      "ランタイム",
	"refactor":     "リファクター",
	"grep":         "グレップ",
	"tmux":         "ティーマックス",
	"worktree":     "ワークツリー",
	"subagent":     "サブエージェント",
	"handoff":      "ハンドオフ",
	"readme":       "リードミー",
	"typecheck":    "タイプチェック",
	"struct":       "ストラクト",
	"mutex":        "ミューテックス",
	"entrypoint":   "エントリーポイント",
	"filepath":     "ファイルパス",
	"timestamp":    "タイムスタンプ",
	"changelog":    "チェンジログ",
	"allowlist":    "アローリスト",
	"localstorage": "ローカルストレージ",
	"stdin":        "スタンダードイン", // 既存 stdout=スタンダードアウト / stderr=スタンダードエラー に揃える
	// UI 語
	"placeholder": "プレースホルダー",
	"popover":     "ポップオーバー",
	"tooltip":     "ツールチップ",
	"dropdown":    "ドロップダウン",
	"viewport":    "ビューポート",
	"frontend":    "フロントエンド",
	"websocket":   "ウェブソケット",
	"dockerfile":  "ドッカーファイル",
	"gzip":        "ジージップ",
	// 外部プロダクト / ツール名
	"opencode": "オープンコード",
	"codex":    "コーデックス",
	"ollama":   "オラマ",
	"voicevox": "ボイスボックス",
	"zundamon": "ずんだもん",
	"marp":     "マープ",
	"xterm":    "エックスターム",
	// 小文字で書かれる略語（大文字なら spellLetters が拾うが、小文字は綴りママになるため明示）
	"mcp": "エムシーピー",
	"llm": "エルエルエム",
	"sdk": "エスディーケー",
	"css": "シーエスエス",
	"svg": "エスブイジー",
	"jsx": "ジェイエスエックス",
	"tsx": "ティーエスエックス",
	"tsc": "ティーエスシー",
	"scm": "エスシーエム",
	"lfs": "エルエフエス",
	"tui": "ティーユーアイ",
	"sso": "エスエスオー",
	"ssh": "エスエスエイチ",
	"tls": "ティーエルエス",
	"jvm": "ジェイブイエム",
	"png": "ピーエヌジー",
	"poc": "ピーオーシー",
	"mvp": "エムブイピー",
	"rtk": "アールティーケー",
	// --- ネットワーク / プロトコル（小文字表記は英字名読みルールが効かないため明示。
	//     http/https/ftp/dns/cd は CMUdict に正しい読みが既にあるため未収載。
	//     arp/nat/sap/sip は CMUdict に「実在の英単語」として載っており誤読されるため
	//     （nat→ナット, sap→サップ 等）、ここで意図的に上書きする） ---
	"https": "エイチティーティーピーエス",
	"tcp":   "ティーシーピー",
	"udp":   "ユーディーピー",
	"sftp":  "エスエフティーピー",
	"smtp":  "エスエムティーピー",
	"imap":  "アイマップ",
	"pop3":  "ピーオーピースリー",
	"ldap":  "エルダップ",
	"saml":  "サムル",
	"oidc":  "オーアイディーシー",
	"mqtt":  "エムキューティーティー",
	"voip":  "ボイップ",
	"rtp":   "アールティーピー",
	"ssl":   "エスエスエル",
	"vpn":   "ブイピーエヌ",
	"cdn":   "シーディーエヌ",
	"waf":   "ダブリューエーエフ",
	"dhcp":  "ディーエイチシーピー",
	"icmp":  "アイシーエムピー",
	"bgp":   "ビージーピー",
	"vlan":  "ブイラン",
	"ntp":   "エヌティーピー",
	"rpc":   "アールピーシー",
	"mtu":   "エムティーユー",
	"arp":   "エーアールピー", // CMUdict は "アープ" と誤読
	"nat":   "エヌエーティー", // CMUdict は "ナット" と誤読
	"sip":   "エスアイピー",  // CMUdict は "シップ" と誤読
	"sap":   "エスエーピー",  // CMUdict は "サップ" と誤読
	// --- 開発 / ビジネス略語（小文字表記のみ。ui/crud/faas は CMUdict の読みで既に
	//     正しいため未収載。roi/seo/saas は CMUdict に実在語として載っており誤読される） ---
	"ux":     "ユーエックス",
	"orm":    "オーアールエム",
	"dto":    "ディーティーオー",
	"mvc":    "エムブイシー",
	"mvvm":   "エムブイブイエム",
	"ssr":    "エスエスアール",
	"ssg":    "エスエスジー",
	"csr":    "シーエスアール",
	"kpi":    "ケーピーアイ",
	"sla":    "エスエルエー",
	"slo":    "エスエルオー",
	"sre":    "エスアールイー",
	"devops": "デブオプス",
	"gitops": "ギットオプス",
	"saas":   "サース", // CMUdict は "サス" と誤読（長音が落ちる）
	"paas":   "パース",
	"iaas":   "アイアース",
	"ci":     "シーアイ",
	"roi":    "アールオーアイ", // CMUdict は人名 "ロイ" と誤読
	"seo":    "エスイーオー",  // CMUdict は "シオ" 寄りに誤読
	// --- 数字入りの略語（トークン全体一致。EC2/route53 と同じ扱い） ---
	"b2b":    "ビーツービー",
	"b2c":    "ビーツーシー",
	"c2c":    "シーツーシー",
	"p2p":    "ピーツーピー",
	"oauth2": "オーオースツー",
	"web3":   "ウェブスリー",
	"gpt":    "ジーピーティー",
	"gpt3":   "ジーピーティースリー",
	"gpt4":   "ジーピーティーフォー",
	// --- 企業 / サービス名（追加分。microsoft/debian/zipkin は CMUdict の読みで既に
	//     正しいため未収載。salesforce/ubuntu は誤差が大きいため明示上書き） ---
	"salesforce": "セールスフォース", // CMUdict は "セイルズフォース" 寄り
	"vmware":     "ブイエムウェア",
	"ubuntu":     "ウブントゥ", // CMUdict は "ウーブートゥー" 寄り
	"centos":     "セントオーエス",
	"alibaba":    "アリババ",
	"tencent":    "テンセント",
	"bytedance":  "バイトダンス",
	"baidu":      "バイドゥ",
	"mercari":    "メルカリ",
	"paypay":     "ペイペイ",
	"cyberagent": "サイバーエージェント",
	"freee":      "フリー",
	"mixi":       "ミクシィ",
	"hatena":     "はてな",
	"pixiv":      "ピクシブ",
	"cookpad":    "クックパッド",
	"dwango":     "ドワンゴ",
	"smartnews":  "スマートニュース",
	"sansan":     "サンサン",
	"abema":      "アベマ",
	// --- クラウド / インフラツール（追加分） ---
	"pulumi":        "プルミ",
	"virtualbox":    "バーチャルボックス",
	"openstack":     "オープンスタック",
	"istio":         "イスティオ",
	"circleci":      "サークルシーアイ",
	"argocd":        "アルゴシーディー",
	"loki":          "ロキ",
	"jaeger":        "イェーガー", // CMUdict は "ジェガー" 寄り
	"newrelic":      "ニューレリック",
	"splunk":        "スプランク",
	"logstash":      "ログスタッシュ",
	"fluentd":       "フルエントディー",
	"fluentbit":     "フルエントビット",
	"opentelemetry": "オープンテレメトリー",
	"otel":          "オーテル",
	"statsd":        "スタッツディー",
	// --- 言語 / フレームワーク（追加分。rust/swift/dart/flutter/unity/perl/haskell 等は
	//     CMUdict の読みで既に正しいため未収載） ---
	"erlang":      "アーラン",
	"clojure":     "クロージャー",
	"django":      "ジャンゴ",
	"laravel":     "ララベル",
	"symfony":     "シンフォニー",
	"xamarin":     "ザマリン",
	"webassembly": "ウェブアセンブリ",
	"wasm":        "ワズム",
	// --- 一般 UI / 開発語（実機フィードバックの読み希望。CMUdict の音写が慣用カタカナから
	//     外れる語を慣用読みで固定する。例: version→CMUdict ヴァージャン, message→メサジ,
	//     session→セシャン, setting→セティング, status→スタタス, daemon→ディーマン, docs→ダクス,
	//     console→カンソール）。派生・複数形は分割が効かず綴りママになるので個別に足す。 ---
	"version":   "バージョン",
	"versions":  "バージョンズ",
	"revision":  "リビジョン",
	"revisions": "リビジョンズ",
	"minor":     "マイナー",
	"major":     "メジャー",
	"patch":     "パッチ",
	"thread":    "スレッド",
	"threads":   "スレッズ",
	"message":   "メッセージ",
	"messages":  "メッセージズ",
	"session":   "セッション",
	"sessions":  "セッションズ",
	"setting":   "セッティング",
	"settings":  "セッティングス",
	"status":    "ステータス",
	"daemon":    "デーモン",
	"daemons":   "デーモンズ",
	"resume":    "レジューム",
	"docs":      "ドックス",
	"accept":    "アクセプト",
	"approve":   "アプルーブ",
	"approved":  "アプルーブド",
	"approval":  "アプルーバル",
	"tests":     "テスツ",
	"read":      "リード",
	"write":     "ライト",
	"console":   "コンソール",
	"httptest":  "エイチティーティーピーテスト",
	// --- 容量・データ量の単位（略語トークン。MiB→メビバイト 等。二進接頭辞（〜ビ）と
	//     十進接頭辞（キロ/メガ…）。キーは小文字化されるので MiB / MB のどちらの表記でも引く）。 ---
	"kib": "キビバイト",
	"mib": "メビバイト",
	"gib": "ギビバイト",
	"tib": "テビバイト",
	"pib": "ペビバイト",
	"kb":  "キロバイト",
	"mb":  "メガバイト",
	"gb":  "ギガバイト",
	"tb":  "テラバイト",
	"pb":  "ペタバイト",
	// --- シグナル（sigkill / sigterm / sigint 等。番号付き sigusr1 等はトークン全体一致で引く）。 ---
	"sigkill": "シグキル",
	"sigterm": "シグターム",
	"sigint":  "シグイント",
	"sighup":  "シグハップ",
	"sigquit": "シグクイット",
	"sigstop": "シグストップ",
	"sigcont": "シグコント",
	"sigsegv": "シグセグブイ",
	"sigabrt": "シグアボート",
	"sigpipe": "シグパイプ",
	"sigchld": "シグチャイルド",
	"sigbus":  "シグバス",
	"sigfpe":  "シグエフピーイー",
	"sigtrap": "シグトラップ",
	"sigalrm": "シグアラーム",
	"sigusr1": "シグユーザーワン",
	"sigusr2": "シグユーザーツー",
	// --- UNIX コマンド / オペレータ用語（提案分。小文字コマンド名は英字名読みルールが効かず
	//     綴りママ／CMUdict の実在語に化けるため明示。慣用の発音で固定）。 ---
	"chmod":      "チェンジモッド",
	"chown":      "チャウン",
	"chgrp":      "チェンジグループ",
	"sudo":       "スードゥー", // 語として読む（su を綴る エスユードゥー ではない）
	"sudoers":    "スードゥアーズ",
	"umask":      "ユーマスク",
	"awk":        "オーク",
	"gawk":       "ゴーク",
	"sed":        "セド",
	"cron":       "クロン",
	"crontab":    "クロンタブ",
	"tar":        "ター",
	"gunzip":     "ガンジップ",
	"bzip2":      "ビージップツー",
	"zstd":       "ゼットエスティーディー",
	"curl":       "カール",
	"wget":       "ダブリューゲット",
	"scp":        "エスシーピー",
	"rsync":      "アールシンク",
	"ping":       "ピング",
	"traceroute": "トレースルート",
	"netstat":    "ネットスタット",
	"ifconfig":   "アイエフコンフィグ",
	"nslookup":   "エヌエスルックアップ",
	"dig":        "ディグ",
	"lsof":       "エルエスオーエフ",
	"xargs":      "エックスアーグス",
	"cd":         "シーディー",
	"ls":         "エルエス",
	"rm":         "アールエム",
	"cp":         "シーピー",
	"mv":         "エムブイ",
	"ln":         "エルエヌ",
	"pwd":        "ピーダブリューディー",
	"mkdir":      "メイクディレクトリ",
	"rmdir":      "アールエムディーアイアール", // 綴り読み（ユーザー希望）
	"init":       "イニット",          // init.d は "." を跨ぐので ttsText 側で別処理
	"df":         "ディーエフ",
	"du":         "ディーユー",
	"ps":         "ピーエス",
	"htop":       "エイチトップ",
	"kill":       "キル",
	"killall":    "キルオール",
	"pkill":      "ピーキル",
	"pgrep":      "ピーグレップ",
	"nohup":      "ノーハップ",
	"fsck":       "エフエスシーケー",
	"umount":     "アンマウント",
	"uname":      "ユーネーム",
	"systemd":    "システムディー",
	"systemctl":  "システムコントロール",  // ctl = control（ユーザー希望）
	"journalctl": "ジャーナルコントロール", // systemctl に合わせる
	"dmesg":      "ディーメッセージ",
	"vim":        "ヴィム",
	"neovim":     "ネオヴィム",
	"emacs":      "イーマックス",
	"bash":       "バッシュ",
	"bashrc":     "バッシュアールシー", // .bashrc もトークンは bashrc なので拾える
	"zsh":        "ゼットエスエイチ",
	"apt":        "アプト",
	"yum":        "ヤム",
	"dnf":        "ディーエヌエフ",
	"pacman":     "パックマン",
	"dpkg":       "ディーピーケージー",
	"rpm":        "アールピーエム",
	"homebrew":   "ホームブリュー",
	"ripgrep":    "リップグレップ",
	"egrep":      "イーグレップ",
	"fgrep":      "エフグレップ",
}

// contractionKana は英語の短縮形（アポストロフィ入り）の読み。CMUdict はこれらを分断読み
// してしまう（"it's"→"イット'エス"、"don't"→"ダン'ティー"）ため、頻出形を慣用カタカナで固定
// する。キーは小文字・ASCII アポストロフィ。ここに無い短縮形/所有格は convertContraction が
// 「元の語＋ズ」や「' 除去」でフォールバックする。**足りない形はここに 1 行足すだけで拡張可。**
var contractionKana = map[string]string{
	// be/have/is の縮約
	"it's":    "イッツ",
	"that's":  "ザッツ",
	"what's":  "ワッツ",
	"let's":   "レッツ",
	"here's":  "ヒアーズ",
	"there's": "ゼアーズ",
	"he's":    "ヒーズ",
	"she's":   "シーズ",
	"who's":   "フーズ",
	"i'm":     "アイム",
	"i've":    "アイブ",
	"i'll":    "アイル",
	"i'd":     "アイド",
	"you're":  "ユア",
	"you've":  "ユーブ",
	"you'll":  "ユール",
	"you'd":   "ユード",
	"we're":   "ウィアー",
	"we've":   "ウィーブ",
	"we'll":   "ウィール",
	"we'd":    "ウィード",
	"they're": "ゼイアー",
	"they've": "ゼイブ",
	"they'll": "ゼイル",
	"they'd":  "ゼイド",
	"it'll":   "イトゥル",
	"it'd":    "イトゥド",
	// not の縮約
	"don't":     "ドント",
	"can't":     "キャント",
	"won't":     "ウォント",
	"isn't":     "イズント",
	"aren't":    "アーント",
	"wasn't":    "ワズント",
	"weren't":   "ワーント",
	"doesn't":   "ダズント",
	"didn't":    "ディドント",
	"hasn't":    "ハズント",
	"haven't":   "ハブント",
	"hadn't":    "ハドント",
	"wouldn't":  "ウドゥント",
	"couldn't":  "クドゥント",
	"shouldn't": "シュドゥント",
	"mustn't":   "マスント",
	"needn't":   "ニードント",
}
