// enkana_dict.go — override table for the English-to-katakana readings in enkana.go. AWS
// service names and developer jargon are either absent from the CMU pronouncing dictionary
// or read differently there than in common usage, so they are pinned here.
// convertWord/convertToken consult this before CMUdict. Keys are lowercase, and the
// conventional Japanese reading wins (json -> ジェイソン, dao -> ダオ); a missing word is one
// more line.
//
// Coverage is deliberately partial — a few hundred hand-curated words. Abbreviation+digit
// forms such as EC2/S3 are handled automatically by the rules in enkana.go, so this table
// holds word-shaped entries.
package main

var techKana = map[string]string{
	// --- Developer jargon / general ---
	"dom":        "ドム",     // CMUdict has the real word dom -> ダム; DOM is conventionally ドム
	"good":       "グッド",    // CMUdict does not geminate the final D and yields "グド"
	"well":       "ウェル",    // A variant reading comes out "ウェルル"; pin the conventional one
	"agent":      "エージェント", // CMUdict misreads it as roughly "エイジャント"
	"manage":     "マネージ",   // CMUdict gives "マナジ..." for the manage family (long vowel lost)
	"managed":    "マネージド",  // e.g. "マネージドサービス"
	"manager":    "マネージャー",
	"managers":   "マネージャーズ",
	"management": "マネジメント", // The one word conventionally without the long vowel (not マネージメント)
	"image":      "イメージ",   // CMUdict misreads it as "イマジ"
	"images":     "イメージズ",  // e.g. Docker images
	"imaging":    "イメージング",
	"dao":        "ダオ",
	"json":       "ジェイソン",
	"yaml":       "ヤムル",
	"yml":        "ヤムル",
	"toml":       "トムル",
	"sql":        "エスキューエル",
	"nosql":      "ノーエスキューエル",
	"graphql":    "グラフキューエル",
	"grpc":       "ジーアールピーシー",
	"api":        "エーピーアイ",
	"rest":       "レスト",
	"url":        "ユーアールエル",
	"uri":        "ユーアールアイ",
	"id":         "アイディー", // CMUdict resolves it as /ɪd/ (イド)
	"uuid":       "ユーユーアイディー",
	"ipv4":       "アイピーブイフォー",
	"ipv6":       "アイピーブイシックス",
	"cli":        "シーエルアイ",
	"gui":        "グーイ",
	"oauth":      "オーオース",
	"origin":     "オリジン",
	"body":       "ボディ",
	"query":      "クエリ",
	"parameter":  "パラメータ",
	"iframe":     "アイフレーム",
	"preview":    "プレビュー",
	"cookie":     "クッキー",
	"httpapi":    "エイチティーティーピーエーピーアイ",
	"repo":       "レポ",
	"repos":      "レポズ",
	"jwt":        "ジェイダブリューティー",
	"regex":      "レジェックス",
	"enum":       "イーナム",
	"async":      "エイシンク",
	"await":      "アウェイト",
	"middleware": "ミドルウェア",
	"webhook":    "ウェブフック",
	"env":        "エンブ",
	"stdout":     "スタンダードアウト",
	"stderr":     "スタンダードエラー",
	// --- Languages / runtimes ---
	"golang":     "ゴーラン",
	"kotlin":     "コトリン",
	"typescript": "タイプスクリプト",
	"javascript": "ジャバスクリプト",
	"nodejs":     "ノードジェイエス",
	"deno":       "ディーノ",
	"php":        "ピーエイチピー",
	"csharp":     "シーシャープ",
	// --- Middleware / tools ---
	"nginx":      "エンジンエックス",
	"redis":      "レディス",
	"kafka":      "カフカ",
	"postgres":   "ポストグレス",
	"postgresql": "ポストグレスキューエル",
	"mysql":      "マイエスキューエル",
	"sqlite":     "エスキューライト",
	"mongodb":    "モンゴディービー",
	"docker":     "ドッカー",
	"kubernetes": "クーバネティス",
	"k8s":        "ケーエイツエス",
	"terraform":  "テラフォーム",
	"ansible":    "アンシブル",
	"grafana":    "グラファナ",
	"prometheus": "プロメテウス",
	"kibana":     "キバナ",
	"jenkins":    "ジェンキンス",
	"gradle":     "グレイドル",
	"maven":      "メイブン",
	"webpack":    "ウェブパック",
	"vite":       "ヴィート",
	"eslint":     "イーエスリント",
	// --- AWS services (EC2/S3-style abbreviations are automatic; these are word forms) ---
	"aws":            "エーダブリューエス",
	"lambda":         "ラムダ",
	"dynamodb":       "ダイナモディービー",
	"cloudfront":     "クラウドフロント",
	"cloudwatch":     "クラウドウォッチ",
	"cloudformation": "クラウドフォーメーション",
	"fargate":        "ファーゲート",
	"cognito":        "コグニート",
	"athena":         "アテナ",
	"redshift":       "レッドシフト",
	"aurora":         "オーロラ",
	"kinesis":        "キネシス",
	"route":          "ルート",
	"route53":        "ルートゴジュウサン",
	"iam":            "アイアム",
	"vpc":            "ブイピーシー",
	"ecs":            "イーシーエス",
	"eks":            "イーケーエス",
	"ecr":            "イーシーアール",
	"rds":            "アールディーエス",
	"sqs":            "エスキューエス",
	"sns":            "エスエヌエス",
	"ssm":            "エスエスエム",
	"efs":            "イーエフエス",
	"ebs":            "イービーエス",
	"kms":            "ケーエムエス",
	"acm":            "エーシーエム",
	"elb":            "イーエルビー",
	"asg":            "エーエスジー",
	"amplify":        "アンプリファイ",
	"bedrock":        "ベッドロック",
	// --- Cloud / hosting ---
	"azure":        "アジュール",
	"gcp":          "ジーシーピー",
	"firebase":     "ファイアベース",
	"vercel":       "ヴァーセル",
	"netlify":      "ネットリファイ",
	"cloudflare":   "クラウドフレア",
	"heroku":       "ヘロク",
	"supabase":     "スーパーベース",
	"digitalocean": "デジタルオーシャン",
	// --- SaaS / services / brands ---
	"google":      "グーグル",
	"wikipedia":   "ウィキペディア",
	"gmail":       "ジーメール",
	"chrome":      "クローム",
	"slack":       "スラック",
	"teams":       "チームズ",
	"zoom":        "ズーム",
	"excel":       "エクセル",
	"word":        "ワード",
	"powerpoint":  "パワーポイント",
	"outlook":     "アウトルック",
	"onedrive":    "ワンドライブ",
	"sharepoint":  "シェアポイント",
	"office":      "オフィス",
	"figma":       "フィグマ",
	"adobe":       "アドビ",
	"photoshop":   "フォトショップ",
	"github":      "ギットハブ",
	"gitlab":      "ギットラボ",
	"bitbucket":   "ビットバケット",
	"jira":        "ジラ",
	"confluence":  "コンフルエンス",
	"atlassian":   "アトラシアン",
	"notion":      "ノーション",
	"trello":      "トレロ",
	"asana":       "アサナ",
	"linear":      "リニア",
	"kintone":     "キントーン",
	"nexmo":       "ネクスモ",
	"sinch":       "シンチ",
	"citic":       "シティック",
	"softbank":    "ソフトバンク", // All-caps SOFTBANK is over 5 letters, so the letter-name rule misses it
	"rakuten":     "ラクテン",
	"docomo":      "ドコモ",
	"au":          "エーユー", // The carrier au; bare URLs are stripped before TTS, so .au domains do not collide
	"ymobile":     "ワイモバイル",
	"dena":        "ディーエヌエー", // camelCase splitting would break DeNA into De/NA
	"gree":        "グリー",
	"sybase":      "サイベース",
	"twiml":       "トゥイムル",
	"8x8":         "エイトバイエイト", // Keys containing digits match the whole token (as ipv4/route53 do)
	"vonage":      "ボネージ",
	"plivo":       "プリボ",
	"messagebird": "メッセージバード",
	"sendgrid":    "センドグリッド",
	"webrtc":      "ウェブアールティーシー",
	"volte":       "ボルテ",
	"freeswitch":  "フリースイッチ",
	"cisco":       "シスコ",
	"ericsson":    "エリクソン",
	"nokia":       "ノキア",
	"huawei":      "ファーウェイ",
	"qualcomm":    "クアルコム",
	"claude":      "クロード",
	"chatgpt":     "チャットジーピーティー",
	"openai":      "オープンエーアイ",
	"anthropic":   "アンスロピック",
	"gemini":      "ジェミニ",
	"copilot":     "コパイロット",
	"cursor":      "カーサー",
	"kiro":        "キロ",
	"datadog":     "データドッグ",
	"sentry":      "セントリー",
	"twilio":      "トゥイリオ",
	"stripe":      "ストライプ",
	"postman":     "ポストマン",
	"vscode":      "ブイエスコード",
	"intellij":    "インテリジェイ",
	"npm":         "エヌピーエム",
	"pnpm":        "ピーエヌピーエム",
	// --- Frameworks / libraries / testing ---
	"react":         "リアクト",
	"nextjs":        "ネクストジェイエス",
	"vue":           "ビュー",
	"angular":       "アンギュラー",
	"svelte":        "スベルト",
	"tailwind":      "テイルウィンド",
	"jest":          "ジェスト",
	"vitest":        "ヴィテスト",
	"cypress":       "サイプレス",
	"playwright":    "プレイライト",
	"swagger":       "スワッガー",
	"openapi":       "オープンエーピーアイ",
	"helm":          "ヘルム",
	"elasticsearch": "エラスティックサーチ",
	"rabbitmq":      "ラビットエムキュー",
	// --- Words a corpus scan found uncovered (docs/log/24): common dev terms, external
	//     product names and lowercase abbreviations that are frequent in the answer text
	//     being spoken yet absent from CMUdict, so they came out spelled as written or
	//     letter by letter. The extraction procedure is enkana_freq's cross-check scan. ---
	// Dev terms (compounds and derivatives are not split by camelCase, so list them)
	"config":       "コンフィグ",
	"runtime":      "ランタイム",
	"refactor":     "リファクター",
	"grep":         "グレップ",
	"tmux":         "ティーマックス",
	"worktree":     "ワークツリー",
	"subagent":     "サブエージェント",
	"handoff":      "ハンドオフ",
	"readme":       "リードミー",
	"typecheck":    "タイプチェック",
	"struct":       "ストラクト",
	"mutex":        "ミューテックス",
	"entrypoint":   "エントリーポイント",
	"filepath":     "ファイルパス",
	"timestamp":    "タイムスタンプ",
	"changelog":    "チェンジログ",
	"allowlist":    "アローリスト",
	"localstorage": "ローカルストレージ",
	"stdin":        "スタンダードイン", // Matches the existing stdout=スタンダードアウト / stderr=スタンダードエラー
	// UI terms
	"placeholder": "プレースホルダー",
	"popover":     "ポップオーバー",
	"tooltip":     "ツールチップ",
	"dropdown":    "ドロップダウン",
	"viewport":    "ビューポート",
	"frontend":    "フロントエンド",
	"websocket":   "ウェブソケット",
	"dockerfile":  "ドッカーファイル",
	"gzip":        "ジージップ",
	// External products / tool names
	"opencode": "オープンコード",
	"codex":    "コーデックス",
	"ollama":   "オラマ",
	"voicevox": "ボイスボックス",
	"zundamon": "ずんだもん",
	"marp":     "マープ",
	"xterm":    "エックスターム",
	// Abbreviations written lowercase; spellLetters covers the uppercase form, lowercase would be spelled as written
	"mcp": "エムシーピー",
	"llm": "エルエルエム",
	"sdk": "エスディーケー",
	"css": "シーエスエス",
	"svg": "エスブイジー",
	"jsx": "ジェイエスエックス",
	"tsx": "ティーエスエックス",
	"tsc": "ティーエスシー",
	"scm": "エスシーエム",
	"lfs": "エルエフエス",
	"tui": "ティーユーアイ",
	"sso": "エスエスオー",
	"ssh": "エスエスエイチ",
	"tls": "ティーエルエス",
	"jvm": "ジェイブイエム",
	"png": "ピーエヌジー",
	"poc": "ピーオーシー",
	"mvp": "エムブイピー",
	"rtk": "アールティーケー",
	// --- Network / protocols. The letter-name rule does not fire on lowercase spellings.
	//     http/https/ftp/dns/cd are left out because CMUdict already reads them correctly.
	//     arp/nat/sap/sip are in CMUdict as real English words and so are misread
	//     (nat -> ナット, sap -> サップ); overriding them here is deliberate. ---
	"https": "エイチティーティーピーエス",
	"tcp":   "ティーシーピー",
	"udp":   "ユーディーピー",
	"sftp":  "エスエフティーピー",
	"smtp":  "エスエムティーピー",
	"imap":  "アイマップ",
	"pop3":  "ピーオーピースリー",
	"ldap":  "エルダップ",
	"saml":  "サムル",
	"oidc":  "オーアイディーシー",
	"mqtt":  "エムキューティーティー",
	"voip":  "ボイップ",
	"rtp":   "アールティーピー",
	"ssl":   "エスエスエル",
	"vpn":   "ブイピーエヌ",
	"cdn":   "シーディーエヌ",
	"waf":   "ダブリューエーエフ",
	"dhcp":  "ディーエイチシーピー",
	"icmp":  "アイシーエムピー",
	"bgp":   "ビージーピー",
	"vlan":  "ブイラン",
	"ntp":   "エヌティーピー",
	"rpc":   "アールピーシー",
	"mtu":   "エムティーユー",
	"arp":   "エーアールピー", // CMUdict misreads it as "アープ"
	"nat":   "エヌエーティー", // CMUdict misreads it as "ナット"
	"sip":   "エスアイピー",  // CMUdict misreads it as "シップ"
	"sap":   "エスエーピー",  // CMUdict misreads it as "サップ"
	// --- Dev / business abbreviations, lowercase spellings only. ui/crud/faas are left out
	//     because CMUdict already reads them correctly; roi/seo/saas are real words there
	//     and are misread. ---
	"ux":     "ユーエックス",
	"orm":    "オーアールエム",
	"dto":    "ディーティーオー",
	"mvc":    "エムブイシー",
	"mvvm":   "エムブイブイエム",
	"ssr":    "エスエスアール",
	"ssg":    "エスエスジー",
	"csr":    "シーエスアール",
	"kpi":    "ケーピーアイ",
	"sla":    "エスエルエー",
	"slo":    "エスエルオー",
	"sre":    "エスアールイー",
	"devops": "デブオプス",
	"gitops": "ギットオプス",
	"saas":   "サース", // CMUdict misreads it as "サス" (long vowel lost)
	"paas":   "パース",
	"iaas":   "アイアース",
	"ci":     "シーアイ",
	"roi":    "アールオーアイ", // CMUdict misreads it as the name "ロイ"
	"seo":    "エスイーオー",  // CMUdict misreads it as roughly "シオ"
	// --- Abbreviations containing digits (whole-token match, as with EC2/route53) ---
	"b2b":    "ビーツービー",
	"b2c":    "ビーツーシー",
	"c2c":    "シーツーシー",
	"p2p":    "ピーツーピー",
	"oauth2": "オーオースツー",
	"web3":   "ウェブスリー",
	"gpt":    "ジーピーティー",
	"gpt3":   "ジーピーティースリー",
	"gpt4":   "ジーピーティーフォー",
	// --- Companies / service names. microsoft/debian/zipkin are left out because CMUdict
	//     already reads them correctly; salesforce/ubuntu are far enough off to override. ---
	"salesforce": "セールスフォース", // CMUdict gives roughly "セイルズフォース"
	"vmware":     "ブイエムウェア",
	"ubuntu":     "ウブントゥ", // CMUdict gives roughly "ウーブートゥー"
	"centos":     "セントオーエス",
	"alibaba":    "アリババ",
	"tencent":    "テンセント",
	"bytedance":  "バイトダンス",
	"baidu":      "バイドゥ",
	"mercari":    "メルカリ",
	"paypay":     "ペイペイ",
	"cyberagent": "サイバーエージェント",
	"freee":      "フリー",
	"mixi":       "ミクシィ",
	"hatena":     "はてな",
	"pixiv":      "ピクシブ",
	"cookpad":    "クックパッド",
	"dwango":     "ドワンゴ",
	"smartnews":  "スマートニュース",
	"sansan":     "サンサン",
	"abema":      "アベマ",
	// --- Cloud / infrastructure tools ---
	"pulumi":        "プルミ",
	"virtualbox":    "バーチャルボックス",
	"openstack":     "オープンスタック",
	"istio":         "イスティオ",
	"circleci":      "サークルシーアイ",
	"argocd":        "アルゴシーディー",
	"loki":          "ロキ",
	"jaeger":        "イェーガー", // CMUdict gives roughly "ジェガー"
	"newrelic":      "ニューレリック",
	"splunk":        "スプランク",
	"logstash":      "ログスタッシュ",
	"fluentd":       "フルエントディー",
	"fluentbit":     "フルエントビット",
	"opentelemetry": "オープンテレメトリー",
	"otel":          "オーテル",
	"statsd":        "スタッツディー",
	// --- Languages / frameworks. rust/swift/dart/flutter/unity/perl/haskell and the like
	//     are left out because CMUdict already reads them correctly. ---
	"erlang":      "アーラン",
	"clojure":     "クロージャー",
	"django":      "ジャンゴ",
	"laravel":     "ララベル",
	"symfony":     "シンフォニー",
	"xamarin":     "ザマリン",
	"webassembly": "ウェブアセンブリ",
	"wasm":        "ワズム",
	// --- General UI / dev terms whose CMUdict transcription drifts from the conventional
	//     katakana, pinned back to the conventional reading. CMUdict gives version→ヴァージャン,
	//     message→メサジ, session→セシャン, setting→セティング, status→スタタス,
	//     daemon→ディーマン, docs→ダクス, console→カンソール. Derivatives and plurals are not
	//     split, so each needs its own entry. ---
	"version":   "バージョン",
	"versions":  "バージョンズ",
	"revision":  "リビジョン",
	"revisions": "リビジョンズ",
	"minor":     "マイナー",
	"major":     "メジャー",
	"patch":     "パッチ",
	"thread":    "スレッド",
	"threads":   "スレッズ",
	"message":   "メッセージ",
	"messages":  "メッセージズ",
	"session":   "セッション",
	"sessions":  "セッションズ",
	"setting":   "セッティング",
	"settings":  "セッティングス",
	"status":    "ステータス",
	"daemon":    "デーモン",
	"daemons":   "デーモンズ",
	"resume":    "レジューム",
	"docs":      "ドックス",
	"accept":    "アクセプト",
	"approve":   "アプルーブ",
	"approved":  "アプルーブド",
	"approval":  "アプルーバル",
	"tests":     "テスツ",
	"read":      "リード",
	"write":     "ライト",
	"console":   "コンソール",
	"httptest":  "エイチティーティーピーテスト",
	// --- Size units as abbreviation tokens (MiB -> メビバイト): binary prefixes (…ビ) and
	//     decimal ones (キロ/メガ…). Keys are lowercased, so MiB and MB both hit. ---
	"kib": "キビバイト",
	"mib": "メビバイト",
	"gib": "ギビバイト",
	"tib": "テビバイト",
	"pib": "ペビバイト",
	"kb":  "キロバイト",
	"mb":  "メガバイト",
	"gb":  "ギガバイト",
	"tb":  "テラバイト",
	"pb":  "ペタバイト",
	// --- Signals. Numbered ones such as sigusr1 are matched as a whole token. ---
	"sigkill": "シグキル",
	"sigterm": "シグターム",
	"sigint":  "シグイント",
	"sighup":  "シグハップ",
	"sigquit": "シグクイット",
	"sigstop": "シグストップ",
	"sigcont": "シグコント",
	"sigsegv": "シグセグブイ",
	"sigabrt": "シグアボート",
	"sigpipe": "シグパイプ",
	"sigchld": "シグチャイルド",
	"sigbus":  "シグバス",
	"sigfpe":  "シグエフピーイー",
	"sigtrap": "シグトラップ",
	"sigalrm": "シグアラーム",
	"sigusr1": "シグユーザーワン",
	"sigusr2": "シグユーザーツー",
	// --- UNIX commands / operator terms. Lowercase command names miss the letter-name rule
	//     and come out spelled as written, or turn into a real CMUdict word; pin the
	//     conventional pronunciation. ---
	"chmod":      "チェンジモッド",
	"chown":      "チャウン",
	"chgrp":      "チェンジグループ",
	"sudo":       "スードゥー", // Read as a word, not spelled out as エスユードゥー
	"sudoers":    "スードゥアーズ",
	"umask":      "ユーマスク",
	"awk":        "オーク",
	"gawk":       "ゴーク",
	"sed":        "セド",
	"cron":       "クロン",
	"crontab":    "クロンタブ",
	"tar":        "ター",
	"gunzip":     "ガンジップ",
	"bzip2":      "ビージップツー",
	"zstd":       "ゼットエスティーディー",
	"curl":       "カール",
	"wget":       "ダブリューゲット",
	"scp":        "エスシーピー",
	"rsync":      "アールシンク",
	"ping":       "ピング",
	"traceroute": "トレースルート",
	"netstat":    "ネットスタット",
	"ifconfig":   "アイエフコンフィグ",
	"nslookup":   "エヌエスルックアップ",
	"dig":        "ディグ",
	"lsof":       "エルエスオーエフ",
	"xargs":      "エックスアーグス",
	"cd":         "シーディー",
	"ls":         "エルエス",
	"rm":         "アールエム",
	"cp":         "シーピー",
	"mv":         "エムブイ",
	"ln":         "エルエヌ",
	"pwd":        "ピーダブリューディー",
	"mkdir":      "メイクディレクトリ",
	"rmdir":      "アールエムディーアイアール", // Spelled out letter by letter
	"init":       "イニット",          // init.d spans a ".", so ttsText handles that separately
	"df":         "ディーエフ",
	"du":         "ディーユー",
	"ps":         "ピーエス",
	"htop":       "エイチトップ",
	"kill":       "キル",
	"killall":    "キルオール",
	"pkill":      "ピーキル",
	"pgrep":      "ピーグレップ",
	"nohup":      "ノーハップ",
	"fsck":       "エフエスシーケー",
	"umount":     "アンマウント",
	"uname":      "ユーネーム",
	"systemd":    "システムディー",
	"systemctl":  "システムコントロール",  // ctl = control
	"journalctl": "ジャーナルコントロール", // Matches systemctl
	"dmesg":      "ディーメッセージ",
	"vim":        "ヴィム",
	"neovim":     "ネオヴィム",
	"emacs":      "イーマックス",
	"bash":       "バッシュ",
	"bashrc":     "バッシュアールシー", // .bashrc tokenizes to bashrc, so it is covered too
	"zsh":        "ゼットエスエイチ",
	"apt":        "アプト",
	"yum":        "ヤム",
	"dnf":        "ディーエヌエフ",
	"pacman":     "パックマン",
	"dpkg":       "ディーピーケージー",
	"rpm":        "アールピーエム",
	"homebrew":   "ホームブリュー",
	"ripgrep":    "リップグレップ",
	"egrep":      "イーグレップ",
	"fgrep":      "エフグレップ",
}

// contractionKana gives the readings for English contractions. CMUdict reads them in
// pieces ("it's" -> "イット'エス", "don't" -> "ダン'ティー"), so the frequent forms are pinned
// to their conventional katakana here. Keys are lowercase with an ASCII apostrophe. A
// contraction or possessive not listed falls back in convertContraction to "base word + ズ"
// or to dropping the apostrophe.
var contractionKana = map[string]string{
	// be/have/is contractions
	"it's":    "イッツ",
	"that's":  "ザッツ",
	"what's":  "ワッツ",
	"let's":   "レッツ",
	"here's":  "ヒアーズ",
	"there's": "ゼアーズ",
	"he's":    "ヒーズ",
	"she's":   "シーズ",
	"who's":   "フーズ",
	"i'm":     "アイム",
	"i've":    "アイブ",
	"i'll":    "アイル",
	"i'd":     "アイド",
	"you're":  "ユア",
	"you've":  "ユーブ",
	"you'll":  "ユール",
	"you'd":   "ユード",
	"we're":   "ウィアー",
	"we've":   "ウィーブ",
	"we'll":   "ウィール",
	"we'd":    "ウィード",
	"they're": "ゼイアー",
	"they've": "ゼイブ",
	"they'll": "ゼイル",
	"they'd":  "ゼイド",
	"it'll":   "イトゥル",
	"it'd":    "イトゥド",
	// not contractions
	"don't":     "ドント",
	"can't":     "キャント",
	"won't":     "ウォント",
	"isn't":     "イズント",
	"aren't":    "アーント",
	"wasn't":    "ワズント",
	"weren't":   "ワーント",
	"doesn't":   "ダズント",
	"didn't":    "ディドント",
	"hasn't":    "ハズント",
	"haven't":   "ハブント",
	"hadn't":    "ハドント",
	"wouldn't":  "ウドゥント",
	"couldn't":  "クドゥント",
	"shouldn't": "シュドゥント",
	"mustn't":   "マスント",
	"needn't":   "ニードント",
}
