#!/usr/bin/env python3
"""Writes or checks the address blocks of the workspace egress-internet NetworkPolicy.

The policy allows the complement of EXCLUDED as separate ipBlocks, none with an `except`.
GKE Dataplane V2 adds a node-identity selector to every ipBlock whose cidr contains a node
address, and an `except` cannot remove it (ADR 0106, addendum of 2026-10-03, #1578): with
`0.0.0.0/0` minus the node range, every node's ports stay reachable from a workspace. So no
allowed block may contain the node range at all, which a fixed complement guarantees as long
as the deployment's ranges lie inside EXCLUDED (Terraform checks that in deploy/gcp/gke).

  egress-blocks.py           check that the egress-internet object is exactly the computed one
  egress-blocks.py --write   rewrite them in place
"""
import ipaddress
import pathlib
import sys

# RFC 1918, shared address space, link-local (the metadata address included). A change here
# changes what every workspace may reach: ADR 0106 decision 7.
EXCLUDED = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "100.64.0.0/10", "169.254.0.0/16"]

POLICY = pathlib.Path(__file__).resolve().parent / "base" / "workspace-networkpolicies.yaml"
BEGIN = "        # BEGIN blocks generated by deploy/kubernetes/egress-blocks.py; do not edit\n"
END = "        # END blocks generated by deploy/kubernetes/egress-blocks.py\n"

# The whole egress-internet object apart from its comments and the blocks. It is checked
# whole because a peer or rule added outside the generated section is just as much an allow:
# one `- ipBlock: {cidr: 0.0.0.0/0}` after END reopens every node.
OBJECT_HEAD = """\
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-internet
  namespace: af-placeholder-ws
spec:
  podSelector:
    matchExpressions:
      - key: agent-fleet.io/workspace
        operator: Exists
  policyTypes: ["Egress"]
  egress:
    - to:
"""


def blocks():
    excluded = [ipaddress.ip_network(c) for c in EXCLUDED]
    out = [ipaddress.ip_network("0.0.0.0/0")]
    for e in excluded:
        nxt = []
        for n in out:
            if not n.overlaps(e):
                nxt.append(n)
            elif e.subnet_of(n):
                nxt.extend(n.address_exclude(e))
            # n inside e: dropped.
        out = nxt
    out = sorted(ipaddress.collapse_addresses(out))

    # The invariants the policy rests on, checked rather than trusted to address_exclude.
    for n in out:
        for e in excluded:
            if n.overlaps(e):
                sys.exit(f"egress-blocks: {n} overlaps excluded {e}")
    total = sum(n.num_addresses for n in out) + sum(
        n.num_addresses for n in ipaddress.collapse_addresses(excluded))
    if total != 2**32:
        sys.exit(f"egress-blocks: blocks and excluded ranges cover {total} addresses, not 2^32")
    return out


def render():
    return BEGIN + "".join(f"        - ipBlock: {{cidr: {n}}}\n" for n in blocks()) + END


def check_object(text):
    """Exits unless the egress-internet object is OBJECT_HEAD plus the blocks, and nothing else."""
    docs = [d for d in text.split("\n---\n") if "\n  name: egress-internet\n" in "\n" + d]
    if len(docs) != 1:
        sys.exit(f"egress-blocks: {POLICY.name} holds {len(docs)} egress-internet objects, not 1")
    have = [l for l in docs[0].splitlines() if l.strip() and not l.lstrip().startswith("#")]
    want = OBJECT_HEAD.splitlines() + [l for l in render().splitlines() if not l.lstrip().startswith("#")]
    if have != want:
        extra = next((h for h, w in zip(have + [""] * len(want), want + [""] * len(have)) if h != w), "")
        sys.exit(f"egress-blocks: the egress-internet object in {POLICY.name} is not exactly the "
                 f"generated policy (first difference: {extra.strip()!r}); nothing may be added "
                 "to it outside the generated section")


def main():
    write = sys.argv[1:] == ["--write"]
    if sys.argv[1:] not in ([], ["--write"]):
        sys.exit(__doc__)
    text = POLICY.read_text()
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        sys.exit(f"egress-blocks: {POLICY} has no generated block section")
    current = text[start:end + len(END)]
    want = render()
    if current == want:
        check_object(text)
        print(f"egress-blocks: {POLICY.name} is up to date ({len(blocks())} blocks)")
        return
    if not write:
        sys.exit(f"egress-blocks: {POLICY.name} differs from the computed blocks; "
                 "run deploy/kubernetes/egress-blocks.py --write")
    text = text[:start] + want + text[end + len(END):]
    check_object(text)
    POLICY.write_text(text)
    print(f"egress-blocks: rewrote {POLICY.name}")


if __name__ == "__main__":
    main()
